// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: account-service/account_service.proto

package account_service

import (
	account "github.com/nicodanke/gesty-api/shared/proto/account-service/requests/account"
	login "github.com/nicodanke/gesty-api/shared/proto/account-service/requests/login"
	permission "github.com/nicodanke/gesty-api/shared/proto/account-service/requests/permission"
	role "github.com/nicodanke/gesty-api/shared/proto/account-service/requests/role"
	user "github.com/nicodanke/gesty-api/shared/proto/account-service/requests/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_account_service_account_service_proto protoreflect.FileDescriptor

const file_account_service_account_service_proto_rawDesc = "" +
	"\n" +
	"%account-service/account_service.proto\x12\x0faccount_service\x1a9account-service/requests/account/rpc_create_account.proto\x1a9account-service/requests/account/rpc_update_account.proto\x1a5account-service/requests/account/rpc_account_me.proto\x1a=account-service/requests/permission/rpc_get_permissions.proto\x1a1account-service/requests/user/rpc_get_users.proto\x1a0account-service/requests/user/rpc_get_user.proto\x1a3account-service/requests/user/rpc_create_user.proto\x1a3account-service/requests/user/rpc_update_user.proto\x1a3account-service/requests/user/rpc_delete_user.proto\x1a0account-service/requests/role/rpc_get_role.proto\x1a1account-service/requests/role/rpc_get_roles.proto\x1a3account-service/requests/role/rpc_create_role.proto\x1a3account-service/requests/role/rpc_update_role.proto\x1a3account-service/requests/role/rpc_delete_role.proto\x1a.account-service/requests/login/rpc_login.proto\x1a6account-service/requests/login/rpc_refresh_token.proto\x1a\x1bgoogle/protobuf/empty.proto2\xdf\x10\n" +
	"\x0eAccountService\x12p\n" +
	"\x05Login\x122.account_service.requests.login.login.LoginRequest\x1a3.account_service.requests.login.login.LoginResponse\x12\x95\x01\n" +
	"\fRefreshToken\x12A.account_service.requests.login.refresh_token.RefreshTokenRequest\x1aB.account_service.requests.login.refresh_token.RefreshTokenResponse\x12\x9e\x01\n" +
	"\rCreateAccount\x12E.account_service.requests.account.create_account.CreateAccountRequest\x1aF.account_service.requests.account.create_account.CreateAccountResponse\x12\x9e\x01\n" +
	"\rUpdateAccount\x12E.account_service.requests.account.update_account.UpdateAccountRequest\x1aF.account_service.requests.account.update_account.UpdateAccountResponse\x12c\n" +
	"\tAccountMe\x12\x16.google.protobuf.Empty\x1a>.account_service.requests.account.account_me.AccountMeResponse\x12z\n" +
	"\aGetUser\x126.account_service.requests.user.get_user.GetUserRequest\x1a7.account_service.requests.user.get_user.GetUserResponse\x12\x7f\n" +
	"\bGetUsers\x128.account_service.requests.user.get_users.GetUsersRequest\x1a9.account_service.requests.user.get_users.GetUsersResponse\x12\x89\x01\n" +
	"\n" +
	"CreateUser\x12<.account_service.requests.user.create_user.CreateUserRequest\x1a=.account_service.requests.user.create_user.CreateUserResponse\x12\x89\x01\n" +
	"\n" +
	"UpdateUser\x12<.account_service.requests.user.update_user.UpdateUserRequest\x1a=.account_service.requests.user.update_user.UpdateUserResponse\x12b\n" +
	"\n" +
	"DeleteUser\x12<.account_service.requests.user.delete_user.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12z\n" +
	"\aGetRole\x126.account_service.requests.role.get_role.GetRoleRequest\x1a7.account_service.requests.role.get_role.GetRoleResponse\x12\x7f\n" +
	"\bGetRoles\x128.account_service.requests.role.get_roles.GetRolesRequest\x1a9.account_service.requests.role.get_roles.GetRolesResponse\x12\x89\x01\n" +
	"\n" +
	"CreateRole\x12<.account_service.requests.role.create_role.CreateRoleRequest\x1a=.account_service.requests.role.create_role.CreateRoleResponse\x12\x89\x01\n" +
	"\n" +
	"UpdateRole\x12<.account_service.requests.role.update_role.UpdateRoleRequest\x1a=.account_service.requests.role.update_role.UpdateRoleResponse\x12b\n" +
	"\n" +
	"DeleteRole\x12<.account_service.requests.role.delete_role.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\x12\xa9\x01\n" +
	"\x0eGetPermissions\x12J.account_service.requests.permission.get_permissions.GetPermissionsRequest\x1aK.account_service.requests.permission.get_permissions.GetPermissionsResponseB=Z;github.com/nicodanke/gesty-api/shared/proto/account-serviceb\x06proto3"

var file_account_service_account_service_proto_goTypes = []any{
	(*login.LoginRequest)(nil),                // 0: account_service.requests.login.login.LoginRequest
	(*login.RefreshTokenRequest)(nil),         // 1: account_service.requests.login.refresh_token.RefreshTokenRequest
	(*account.CreateAccountRequest)(nil),      // 2: account_service.requests.account.create_account.CreateAccountRequest
	(*account.UpdateAccountRequest)(nil),      // 3: account_service.requests.account.update_account.UpdateAccountRequest
	(*emptypb.Empty)(nil),                     // 4: google.protobuf.Empty
	(*user.GetUserRequest)(nil),               // 5: account_service.requests.user.get_user.GetUserRequest
	(*user.GetUsersRequest)(nil),              // 6: account_service.requests.user.get_users.GetUsersRequest
	(*user.CreateUserRequest)(nil),            // 7: account_service.requests.user.create_user.CreateUserRequest
	(*user.UpdateUserRequest)(nil),            // 8: account_service.requests.user.update_user.UpdateUserRequest
	(*user.DeleteUserRequest)(nil),            // 9: account_service.requests.user.delete_user.DeleteUserRequest
	(*role.GetRoleRequest)(nil),               // 10: account_service.requests.role.get_role.GetRoleRequest
	(*role.GetRolesRequest)(nil),              // 11: account_service.requests.role.get_roles.GetRolesRequest
	(*role.CreateRoleRequest)(nil),            // 12: account_service.requests.role.create_role.CreateRoleRequest
	(*role.UpdateRoleRequest)(nil),            // 13: account_service.requests.role.update_role.UpdateRoleRequest
	(*role.DeleteRoleRequest)(nil),            // 14: account_service.requests.role.delete_role.DeleteRoleRequest
	(*permission.GetPermissionsRequest)(nil),  // 15: account_service.requests.permission.get_permissions.GetPermissionsRequest
	(*login.LoginResponse)(nil),               // 16: account_service.requests.login.login.LoginResponse
	(*login.RefreshTokenResponse)(nil),        // 17: account_service.requests.login.refresh_token.RefreshTokenResponse
	(*account.CreateAccountResponse)(nil),     // 18: account_service.requests.account.create_account.CreateAccountResponse
	(*account.UpdateAccountResponse)(nil),     // 19: account_service.requests.account.update_account.UpdateAccountResponse
	(*account.AccountMeResponse)(nil),         // 20: account_service.requests.account.account_me.AccountMeResponse
	(*user.GetUserResponse)(nil),              // 21: account_service.requests.user.get_user.GetUserResponse
	(*user.GetUsersResponse)(nil),             // 22: account_service.requests.user.get_users.GetUsersResponse
	(*user.CreateUserResponse)(nil),           // 23: account_service.requests.user.create_user.CreateUserResponse
	(*user.UpdateUserResponse)(nil),           // 24: account_service.requests.user.update_user.UpdateUserResponse
	(*role.GetRoleResponse)(nil),              // 25: account_service.requests.role.get_role.GetRoleResponse
	(*role.GetRolesResponse)(nil),             // 26: account_service.requests.role.get_roles.GetRolesResponse
	(*role.CreateRoleResponse)(nil),           // 27: account_service.requests.role.create_role.CreateRoleResponse
	(*role.UpdateRoleResponse)(nil),           // 28: account_service.requests.role.update_role.UpdateRoleResponse
	(*permission.GetPermissionsResponse)(nil), // 29: account_service.requests.permission.get_permissions.GetPermissionsResponse
}
var file_account_service_account_service_proto_depIdxs = []int32{
	0,  // 0: account_service.AccountService.Login:input_type -> account_service.requests.login.login.LoginRequest
	1,  // 1: account_service.AccountService.RefreshToken:input_type -> account_service.requests.login.refresh_token.RefreshTokenRequest
	2,  // 2: account_service.AccountService.CreateAccount:input_type -> account_service.requests.account.create_account.CreateAccountRequest
	3,  // 3: account_service.AccountService.UpdateAccount:input_type -> account_service.requests.account.update_account.UpdateAccountRequest
	4,  // 4: account_service.AccountService.AccountMe:input_type -> google.protobuf.Empty
	5,  // 5: account_service.AccountService.GetUser:input_type -> account_service.requests.user.get_user.GetUserRequest
	6,  // 6: account_service.AccountService.GetUsers:input_type -> account_service.requests.user.get_users.GetUsersRequest
	7,  // 7: account_service.AccountService.CreateUser:input_type -> account_service.requests.user.create_user.CreateUserRequest
	8,  // 8: account_service.AccountService.UpdateUser:input_type -> account_service.requests.user.update_user.UpdateUserRequest
	9,  // 9: account_service.AccountService.DeleteUser:input_type -> account_service.requests.user.delete_user.DeleteUserRequest
	10, // 10: account_service.AccountService.GetRole:input_type -> account_service.requests.role.get_role.GetRoleRequest
	11, // 11: account_service.AccountService.GetRoles:input_type -> account_service.requests.role.get_roles.GetRolesRequest
	12, // 12: account_service.AccountService.CreateRole:input_type -> account_service.requests.role.create_role.CreateRoleRequest
	13, // 13: account_service.AccountService.UpdateRole:input_type -> account_service.requests.role.update_role.UpdateRoleRequest
	14, // 14: account_service.AccountService.DeleteRole:input_type -> account_service.requests.role.delete_role.DeleteRoleRequest
	15, // 15: account_service.AccountService.GetPermissions:input_type -> account_service.requests.permission.get_permissions.GetPermissionsRequest
	16, // 16: account_service.AccountService.Login:output_type -> account_service.requests.login.login.LoginResponse
	17, // 17: account_service.AccountService.RefreshToken:output_type -> account_service.requests.login.refresh_token.RefreshTokenResponse
	18, // 18: account_service.AccountService.CreateAccount:output_type -> account_service.requests.account.create_account.CreateAccountResponse
	19, // 19: account_service.AccountService.UpdateAccount:output_type -> account_service.requests.account.update_account.UpdateAccountResponse
	20, // 20: account_service.AccountService.AccountMe:output_type -> account_service.requests.account.account_me.AccountMeResponse
	21, // 21: account_service.AccountService.GetUser:output_type -> account_service.requests.user.get_user.GetUserResponse
	22, // 22: account_service.AccountService.GetUsers:output_type -> account_service.requests.user.get_users.GetUsersResponse
	23, // 23: account_service.AccountService.CreateUser:output_type -> account_service.requests.user.create_user.CreateUserResponse
	24, // 24: account_service.AccountService.UpdateUser:output_type -> account_service.requests.user.update_user.UpdateUserResponse
	4,  // 25: account_service.AccountService.DeleteUser:output_type -> google.protobuf.Empty
	25, // 26: account_service.AccountService.GetRole:output_type -> account_service.requests.role.get_role.GetRoleResponse
	26, // 27: account_service.AccountService.GetRoles:output_type -> account_service.requests.role.get_roles.GetRolesResponse
	27, // 28: account_service.AccountService.CreateRole:output_type -> account_service.requests.role.create_role.CreateRoleResponse
	28, // 29: account_service.AccountService.UpdateRole:output_type -> account_service.requests.role.update_role.UpdateRoleResponse
	4,  // 30: account_service.AccountService.DeleteRole:output_type -> google.protobuf.Empty
	29, // 31: account_service.AccountService.GetPermissions:output_type -> account_service.requests.permission.get_permissions.GetPermissionsResponse
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_account_service_account_service_proto_init() }
func file_account_service_account_service_proto_init() {
	if File_account_service_account_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_account_service_proto_rawDesc), len(file_account_service_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_service_account_service_proto_goTypes,
		DependencyIndexes: file_account_service_account_service_proto_depIdxs,
	}.Build()
	File_account_service_account_service_proto = out.File
	file_account_service_account_service_proto_goTypes = nil
	file_account_service_account_service_proto_depIdxs = nil
}
