// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: account-service/account_service.proto

package account_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	account "shared/proto/account-service/requests/account"
	login "shared/proto/account-service/requests/login"
	role "shared/proto/account-service/requests/role"
	user "shared/proto/account-service/requests/user"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_account_service_account_service_proto protoreflect.FileDescriptor

const file_account_service_account_service_proto_rawDesc = "" +
	"\n" +
	"%account-service/account_service.proto\x12\x0faccount_service\x1a9account-service/requests/account/rpc_create_account.proto\x1a9account-service/requests/account/rpc_update_account.proto\x1a1account-service/requests/user/rpc_get_users.proto\x1a3account-service/requests/user/rpc_create_user.proto\x1a3account-service/requests/user/rpc_delete_user.proto\x1a1account-service/requests/role/rpc_get_roles.proto\x1a3account-service/requests/role/rpc_create_role.proto\x1a3account-service/requests/role/rpc_delete_role.proto\x1a.account-service/requests/login/rpc_login.proto\x1a6account-service/requests/login/rpc_refresh_token.proto\x1a\x1bgoogle/protobuf/empty.proto2\xbe\n" +
	"\n" +
	"\x0eAccountService\x12p\n" +
	"\x05Login\x122.account_service.requests.login.login.LoginRequest\x1a3.account_service.requests.login.login.LoginResponse\x12\x95\x01\n" +
	"\fRefreshToken\x12A.account_service.requests.login.refresh_token.RefreshTokenRequest\x1aB.account_service.requests.login.refresh_token.RefreshTokenResponse\x12\x9e\x01\n" +
	"\rCreateAccount\x12E.account_service.requests.account.create_account.CreateAccountRequest\x1aF.account_service.requests.account.create_account.CreateAccountResponse\x12\x9e\x01\n" +
	"\rUpdateAccount\x12E.account_service.requests.account.update_account.UpdateAccountRequest\x1aF.account_service.requests.account.update_account.UpdateAccountResponse\x12\x7f\n" +
	"\bGetUsers\x128.account_service.requests.user.get_users.GetUsersRequest\x1a9.account_service.requests.user.get_users.GetUsersResponse\x12\x89\x01\n" +
	"\n" +
	"CreateUser\x12<.account_service.requests.user.create_user.CreateUserRequest\x1a=.account_service.requests.user.create_user.CreateUserResponse\x12b\n" +
	"\n" +
	"DeleteUser\x12<.account_service.requests.user.delete_user.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12\x7f\n" +
	"\bGetRoles\x128.account_service.requests.role.get_roles.GetRolesRequest\x1a9.account_service.requests.role.get_roles.GetRolesResponse\x12\x89\x01\n" +
	"\n" +
	"CreateRole\x12<.account_service.requests.role.create_role.CreateRoleRequest\x1a=.account_service.requests.role.create_role.CreateRoleResponse\x12b\n" +
	"\n" +
	"DeleteRole\x12<.account_service.requests.role.delete_role.DeleteRoleRequest\x1a\x16.google.protobuf.EmptyB\x1eZ\x1cshared/proto/account-serviceb\x06proto3"

var file_account_service_account_service_proto_goTypes = []any{
	(*login.LoginRequest)(nil),            // 0: account_service.requests.login.login.LoginRequest
	(*login.RefreshTokenRequest)(nil),     // 1: account_service.requests.login.refresh_token.RefreshTokenRequest
	(*account.CreateAccountRequest)(nil),  // 2: account_service.requests.account.create_account.CreateAccountRequest
	(*account.UpdateAccountRequest)(nil),  // 3: account_service.requests.account.update_account.UpdateAccountRequest
	(*user.GetUsersRequest)(nil),          // 4: account_service.requests.user.get_users.GetUsersRequest
	(*user.CreateUserRequest)(nil),        // 5: account_service.requests.user.create_user.CreateUserRequest
	(*user.DeleteUserRequest)(nil),        // 6: account_service.requests.user.delete_user.DeleteUserRequest
	(*role.GetRolesRequest)(nil),          // 7: account_service.requests.role.get_roles.GetRolesRequest
	(*role.CreateRoleRequest)(nil),        // 8: account_service.requests.role.create_role.CreateRoleRequest
	(*role.DeleteRoleRequest)(nil),        // 9: account_service.requests.role.delete_role.DeleteRoleRequest
	(*login.LoginResponse)(nil),           // 10: account_service.requests.login.login.LoginResponse
	(*login.RefreshTokenResponse)(nil),    // 11: account_service.requests.login.refresh_token.RefreshTokenResponse
	(*account.CreateAccountResponse)(nil), // 12: account_service.requests.account.create_account.CreateAccountResponse
	(*account.UpdateAccountResponse)(nil), // 13: account_service.requests.account.update_account.UpdateAccountResponse
	(*user.GetUsersResponse)(nil),         // 14: account_service.requests.user.get_users.GetUsersResponse
	(*user.CreateUserResponse)(nil),       // 15: account_service.requests.user.create_user.CreateUserResponse
	(*emptypb.Empty)(nil),                 // 16: google.protobuf.Empty
	(*role.GetRolesResponse)(nil),         // 17: account_service.requests.role.get_roles.GetRolesResponse
	(*role.CreateRoleResponse)(nil),       // 18: account_service.requests.role.create_role.CreateRoleResponse
}
var file_account_service_account_service_proto_depIdxs = []int32{
	0,  // 0: account_service.AccountService.Login:input_type -> account_service.requests.login.login.LoginRequest
	1,  // 1: account_service.AccountService.RefreshToken:input_type -> account_service.requests.login.refresh_token.RefreshTokenRequest
	2,  // 2: account_service.AccountService.CreateAccount:input_type -> account_service.requests.account.create_account.CreateAccountRequest
	3,  // 3: account_service.AccountService.UpdateAccount:input_type -> account_service.requests.account.update_account.UpdateAccountRequest
	4,  // 4: account_service.AccountService.GetUsers:input_type -> account_service.requests.user.get_users.GetUsersRequest
	5,  // 5: account_service.AccountService.CreateUser:input_type -> account_service.requests.user.create_user.CreateUserRequest
	6,  // 6: account_service.AccountService.DeleteUser:input_type -> account_service.requests.user.delete_user.DeleteUserRequest
	7,  // 7: account_service.AccountService.GetRoles:input_type -> account_service.requests.role.get_roles.GetRolesRequest
	8,  // 8: account_service.AccountService.CreateRole:input_type -> account_service.requests.role.create_role.CreateRoleRequest
	9,  // 9: account_service.AccountService.DeleteRole:input_type -> account_service.requests.role.delete_role.DeleteRoleRequest
	10, // 10: account_service.AccountService.Login:output_type -> account_service.requests.login.login.LoginResponse
	11, // 11: account_service.AccountService.RefreshToken:output_type -> account_service.requests.login.refresh_token.RefreshTokenResponse
	12, // 12: account_service.AccountService.CreateAccount:output_type -> account_service.requests.account.create_account.CreateAccountResponse
	13, // 13: account_service.AccountService.UpdateAccount:output_type -> account_service.requests.account.update_account.UpdateAccountResponse
	14, // 14: account_service.AccountService.GetUsers:output_type -> account_service.requests.user.get_users.GetUsersResponse
	15, // 15: account_service.AccountService.CreateUser:output_type -> account_service.requests.user.create_user.CreateUserResponse
	16, // 16: account_service.AccountService.DeleteUser:output_type -> google.protobuf.Empty
	17, // 17: account_service.AccountService.GetRoles:output_type -> account_service.requests.role.get_roles.GetRolesResponse
	18, // 18: account_service.AccountService.CreateRole:output_type -> account_service.requests.role.create_role.CreateRoleResponse
	16, // 19: account_service.AccountService.DeleteRole:output_type -> google.protobuf.Empty
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_account_service_account_service_proto_init() }
func file_account_service_account_service_proto_init() {
	if File_account_service_account_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_account_service_proto_rawDesc), len(file_account_service_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_service_account_service_proto_goTypes,
		DependencyIndexes: file_account_service_account_service_proto_depIdxs,
	}.Build()
	File_account_service_account_service_proto = out.File
	file_account_service_account_service_proto_goTypes = nil
	file_account_service_account_service_proto_depIdxs = nil
}
