services:
  reverse-proxy:
    image: traefik:v3.2
    networks:
      - traefik-net
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.api.address=:80
      - --entrypoints.sse.address=:8085
      - --entrypoints.sse.transport.respondingTimeouts.idleTimeout=0
    ports:
      - "80:80"
      - "8080:8080"
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  account-service:
    build:
      context: .
      dockerfile: services/account-service/Dockerfile
    container_name: account-service
    networks:
      - traefik-net
    environment:
     - GESTY_ENVIRONMENT=dev-docker
    labels:
      - "traefik.http.routers.account.entrypoints=api"
      - "traefik.http.routers.account.rule=
          PathPrefix(`/v1/account`) ||
          PathPrefix(`/v1/users`) ||
          PathPrefix(`/v1/roles`) ||
          PathPrefix(`/v1/permissions`) ||
          PathPrefix(`/v1/auth/login`) ||
          PathPrefix(`/v1/auth/refresh`)
          "
      - "traefik.http.routers.account.service=account-service"
      - "traefik.http.services.account-service.loadbalancer.server.port=8081"
      - "traefik.http.routers.account-sse.entrypoints=sse"
      - "traefik.http.routers.account-sse.rule=Path(`/account/events`)"
      - "traefik.http.routers.account-sse.service=account-sse-service"
      - "traefik.http.routers.account-sse.middlewares=strip-app@docker"
      - "traefik.http.middlewares.strip-app.stripprefix.prefixes=/account"
      - "traefik.http.services.account-sse-service.loadbalancer.server.port=8085"
    depends_on:
      db-account:
        condition: service_healthy

  db-account:
    image: postgres
    user: postgres
    networks:
      - traefik-net
    volumes:
      - db-data-account:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=account
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    ports:
      - "5432:5432"
    secrets:
       - db_password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data-account:

secrets:
  db_password:
    file: db_password.txt

networks:
  traefik-net:
    external: true
