services:
  reverse-proxy:
    image: traefik:v3.2
    networks:
      - traefik-net
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.api.address=:80
      - --entrypoints.sse.address=:8085
      - --entrypoints.sse.transport.respondingTimeouts.idleTimeout=0
    ports:
      - "80:80"
      - "8080:8080"
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  account-service:
    build:
      context: .
      dockerfile: services/account-service/Dockerfile
    container_name: account-service
    networks:
      - traefik-net
    environment:
     - GESTY_ENVIRONMENT=prod-docker
    labels:
      - "traefik.http.routers.account.entrypoints=api"
      - "traefik.http.routers.account.rule=
          PathPrefix(`/v1/account`) ||
          PathPrefix(`/v1/users`) ||
          PathPrefix(`/v1/roles`) ||
          PathPrefix(`/v1/permissions`) ||
          PathPrefix(`/v1/auth/login`) ||
          PathPrefix(`/v1/auth/refresh`)
          "
      - "traefik.http.routers.account.service=account-service"
      - "traefik.http.services.account-service.loadbalancer.server.port=8081"
      - "traefik.http.routers.account-sse.entrypoints=sse"
      - "traefik.http.routers.account-sse.rule=Path(`/account/events`)"
      - "traefik.http.routers.account-sse.service=account-sse-service"
      - "traefik.http.routers.account-sse.middlewares=strip-app-account@docker"
      - "traefik.http.middlewares.strip-app-account.stripprefix.prefixes=/account"
      - "traefik.http.services.account-sse-service.loadbalancer.server.port=8085"

  employee-service:
    build:
      context: .
      dockerfile: services/employee-service/Dockerfile
    container_name: employee-service
    networks:
      - traefik-net
    environment:
     - GESTY_ENVIRONMENT=prod-docker
    labels:
      - "traefik.http.routers.employee.entrypoints=api"
      - "traefik.http.routers.employee.rule=
          PathPrefix(`/v1/actions`) ||
          PathPrefix(`/v1/attendances`) ||
          PathPrefix(`/v1/employees`) ||
          PathPrefix(`/v1/devices`) ||
          PathPrefix(`/v1/facilities`)
          "
      - "traefik.http.routers.employee.service=employee-service"
      - "traefik.http.services.employee-service.loadbalancer.server.port=8081"
      - "traefik.http.routers.employee-sse.entrypoints=sse"
      - "traefik.http.routers.employee-sse.rule=Path(`/employee/events`)"
      - "traefik.http.routers.employee-sse.service=employee-sse-service"
      - "traefik.http.routers.employee-sse.middlewares=strip-app-employee@docker"
      - "traefik.http.middlewares.strip-app-employee.stripprefix.prefixes=/employee"
      - "traefik.http.services.employee-sse-service.loadbalancer.server.port=8085"

  deepface-service:
    build:
      context: ./services/deepface-service
      dockerfile: Dockerfile
    container_name: deepface-service
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
