// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/employee_service.proto

package employee_service

import (
	action "github.com/nicodanke/gesty-api/shared/proto/employee-service/requests/action"
	device "github.com/nicodanke/gesty-api/shared/proto/employee-service/requests/device"
	employee "github.com/nicodanke/gesty-api/shared/proto/employee-service/requests/employee"
	facility "github.com/nicodanke/gesty-api/shared/proto/employee-service/requests/facility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_employee_service_employee_service_proto protoreflect.FileDescriptor

const file_employee_service_employee_service_proto_rawDesc = "" +
	"\n" +
	"'employee-service/employee_service.proto\x12\x10employee_service\x1a6employee-service/requests/action/rpc_get_actions.proto\x1a5employee-service/requests/action/rpc_get_action.proto\x1a8employee-service/requests/action/rpc_create_action.proto\x1a8employee-service/requests/action/rpc_update_action.proto\x1a8employee-service/requests/action/rpc_delete_action.proto\x1a6employee-service/requests/device/rpc_get_devices.proto\x1a5employee-service/requests/device/rpc_get_device.proto\x1a8employee-service/requests/device/rpc_create_device.proto\x1a8employee-service/requests/device/rpc_update_device.proto\x1a8employee-service/requests/device/rpc_delete_device.proto\x1aCemployee-service/requests/device/rpc_generate_activation_code.proto\x1a:employee-service/requests/device/rpc_activate_device.proto\x1a?employee-service/requests/device/rpc_refresh_device_token.proto\x1a:employee-service/requests/employee/rpc_get_employees.proto\x1a9employee-service/requests/employee/rpc_get_employee.proto\x1a<employee-service/requests/employee/rpc_create_employee.proto\x1a<employee-service/requests/employee/rpc_update_employee.proto\x1a<employee-service/requests/employee/rpc_delete_employee.proto\x1a;employee-service/requests/facility/rpc_get_facilities.proto\x1a9employee-service/requests/facility/rpc_get_facility.proto\x1a<employee-service/requests/facility/rpc_create_facility.proto\x1a<employee-service/requests/facility/rpc_update_facility.proto\x1a<employee-service/requests/facility/rpc_delete_facility.proto\x1a\x1bgoogle/protobuf/empty.proto2\xd8\x1b\n" +
	"\x0fEmployeeService\x12\x8a\x01\n" +
	"\tGetAction\x12=.employee_service.requests.action.get_action.GetActionRequest\x1a>.employee_service.requests.action.get_action.GetActionResponse\x12\x8f\x01\n" +
	"\n" +
	"GetActions\x12?.employee_service.requests.action.get_actions.GetActionsRequest\x1a@.employee_service.requests.action.get_actions.GetActionsResponse\x12\x99\x01\n" +
	"\fCreateAction\x12C.employee_service.requests.action.create_action.CreateActionRequest\x1aD.employee_service.requests.action.create_action.CreateActionResponse\x12\x99\x01\n" +
	"\fUpdateAction\x12C.employee_service.requests.action.update_action.UpdateActionRequest\x1aD.employee_service.requests.action.update_action.UpdateActionResponse\x12k\n" +
	"\fDeleteAction\x12C.employee_service.requests.action.delete_action.DeleteActionRequest\x1a\x16.google.protobuf.Empty\x12\x98\x01\n" +
	"\vGetFacility\x12C.employee_service.requests.facility.get_facility.GetFacilityRequest\x1aD.employee_service.requests.facility.get_facility.GetFacilityResponse\x12\xa2\x01\n" +
	"\rGetFacilities\x12G.employee_service.requests.facility.get_facilities.GetFacilitiesRequest\x1aH.employee_service.requests.facility.get_facilities.GetFacilitiesResponse\x12\xa7\x01\n" +
	"\x0eCreateFacility\x12I.employee_service.requests.facility.create_facility.CreateFacilityRequest\x1aJ.employee_service.requests.facility.create_facility.CreateFacilityResponse\x12\xa7\x01\n" +
	"\x0eUpdateFacility\x12I.employee_service.requests.facility.update_facility.UpdateFacilityRequest\x1aJ.employee_service.requests.facility.update_facility.UpdateFacilityResponse\x12s\n" +
	"\x0eDeleteFacility\x12I.employee_service.requests.facility.delete_facility.DeleteFacilityRequest\x1a\x16.google.protobuf.Empty\x12\x98\x01\n" +
	"\vGetEmployee\x12C.employee_service.requests.employee.get_employee.GetEmployeeRequest\x1aD.employee_service.requests.employee.get_employee.GetEmployeeResponse\x12\x9d\x01\n" +
	"\fGetEmployees\x12E.employee_service.requests.employee.get_employees.GetEmployeesRequest\x1aF.employee_service.requests.employee.get_employees.GetEmployeesResponse\x12\xa7\x01\n" +
	"\x0eCreateEmployee\x12I.employee_service.requests.employee.create_employee.CreateEmployeeRequest\x1aJ.employee_service.requests.employee.create_employee.CreateEmployeeResponse\x12\xa7\x01\n" +
	"\x0eUpdateEmployee\x12I.employee_service.requests.employee.update_employee.UpdateEmployeeRequest\x1aJ.employee_service.requests.employee.update_employee.UpdateEmployeeResponse\x12s\n" +
	"\x0eDeleteEmployee\x12I.employee_service.requests.employee.delete_employee.DeleteEmployeeRequest\x1a\x16.google.protobuf.Empty\x12\x8a\x01\n" +
	"\tGetDevice\x12=.employee_service.requests.device.get_device.GetDeviceRequest\x1a>.employee_service.requests.device.get_device.GetDeviceResponse\x12\x8f\x01\n" +
	"\n" +
	"GetDevices\x12?.employee_service.requests.device.get_devices.GetDevicesRequest\x1a@.employee_service.requests.device.get_devices.GetDevicesResponse\x12\x99\x01\n" +
	"\fCreateDevice\x12C.employee_service.requests.device.create_device.CreateDeviceRequest\x1aD.employee_service.requests.device.create_device.CreateDeviceResponse\x12\x99\x01\n" +
	"\fUpdateDevice\x12C.employee_service.requests.device.update_device.UpdateDeviceRequest\x1aD.employee_service.requests.device.update_device.UpdateDeviceResponse\x12k\n" +
	"\fDeleteDevice\x12C.employee_service.requests.device.delete_device.DeleteDeviceRequest\x1a\x16.google.protobuf.Empty\x12\xcd\x01\n" +
	"\x16GenerateActivationCode\x12X.employee_service.requests.device.generate_activation_code.GenerateActivationCodeRequest\x1aY.employee_service.requests.device.generate_activation_code.GenerateActivationCodeResponse\x12\xa3\x01\n" +
	"\x0eActivateDevice\x12G.employee_service.requests.device.activate_device.ActivateDeviceRequest\x1aH.employee_service.requests.device.activate_device.ActivateDeviceResponse\x12\xb9\x01\n" +
	"\x12RefreshDeviceToken\x12P.employee_service.requests.device.refresh_device_token.RefreshDeviceTokenRequest\x1aQ.employee_service.requests.device.refresh_device_token.RefreshDeviceTokenResponseB>Z<github.com/nicodanke/gesty-api/shared/proto/employee-serviceb\x06proto3"

var file_employee_service_employee_service_proto_goTypes = []any{
	(*action.GetActionRequest)(nil),               // 0: employee_service.requests.action.get_action.GetActionRequest
	(*action.GetActionsRequest)(nil),              // 1: employee_service.requests.action.get_actions.GetActionsRequest
	(*action.CreateActionRequest)(nil),            // 2: employee_service.requests.action.create_action.CreateActionRequest
	(*action.UpdateActionRequest)(nil),            // 3: employee_service.requests.action.update_action.UpdateActionRequest
	(*action.DeleteActionRequest)(nil),            // 4: employee_service.requests.action.delete_action.DeleteActionRequest
	(*facility.GetFacilityRequest)(nil),           // 5: employee_service.requests.facility.get_facility.GetFacilityRequest
	(*facility.GetFacilitiesRequest)(nil),         // 6: employee_service.requests.facility.get_facilities.GetFacilitiesRequest
	(*facility.CreateFacilityRequest)(nil),        // 7: employee_service.requests.facility.create_facility.CreateFacilityRequest
	(*facility.UpdateFacilityRequest)(nil),        // 8: employee_service.requests.facility.update_facility.UpdateFacilityRequest
	(*facility.DeleteFacilityRequest)(nil),        // 9: employee_service.requests.facility.delete_facility.DeleteFacilityRequest
	(*employee.GetEmployeeRequest)(nil),           // 10: employee_service.requests.employee.get_employee.GetEmployeeRequest
	(*employee.GetEmployeesRequest)(nil),          // 11: employee_service.requests.employee.get_employees.GetEmployeesRequest
	(*employee.CreateEmployeeRequest)(nil),        // 12: employee_service.requests.employee.create_employee.CreateEmployeeRequest
	(*employee.UpdateEmployeeRequest)(nil),        // 13: employee_service.requests.employee.update_employee.UpdateEmployeeRequest
	(*employee.DeleteEmployeeRequest)(nil),        // 14: employee_service.requests.employee.delete_employee.DeleteEmployeeRequest
	(*device.GetDeviceRequest)(nil),               // 15: employee_service.requests.device.get_device.GetDeviceRequest
	(*device.GetDevicesRequest)(nil),              // 16: employee_service.requests.device.get_devices.GetDevicesRequest
	(*device.CreateDeviceRequest)(nil),            // 17: employee_service.requests.device.create_device.CreateDeviceRequest
	(*device.UpdateDeviceRequest)(nil),            // 18: employee_service.requests.device.update_device.UpdateDeviceRequest
	(*device.DeleteDeviceRequest)(nil),            // 19: employee_service.requests.device.delete_device.DeleteDeviceRequest
	(*device.GenerateActivationCodeRequest)(nil),  // 20: employee_service.requests.device.generate_activation_code.GenerateActivationCodeRequest
	(*device.ActivateDeviceRequest)(nil),          // 21: employee_service.requests.device.activate_device.ActivateDeviceRequest
	(*device.RefreshDeviceTokenRequest)(nil),      // 22: employee_service.requests.device.refresh_device_token.RefreshDeviceTokenRequest
	(*action.GetActionResponse)(nil),              // 23: employee_service.requests.action.get_action.GetActionResponse
	(*action.GetActionsResponse)(nil),             // 24: employee_service.requests.action.get_actions.GetActionsResponse
	(*action.CreateActionResponse)(nil),           // 25: employee_service.requests.action.create_action.CreateActionResponse
	(*action.UpdateActionResponse)(nil),           // 26: employee_service.requests.action.update_action.UpdateActionResponse
	(*emptypb.Empty)(nil),                         // 27: google.protobuf.Empty
	(*facility.GetFacilityResponse)(nil),          // 28: employee_service.requests.facility.get_facility.GetFacilityResponse
	(*facility.GetFacilitiesResponse)(nil),        // 29: employee_service.requests.facility.get_facilities.GetFacilitiesResponse
	(*facility.CreateFacilityResponse)(nil),       // 30: employee_service.requests.facility.create_facility.CreateFacilityResponse
	(*facility.UpdateFacilityResponse)(nil),       // 31: employee_service.requests.facility.update_facility.UpdateFacilityResponse
	(*employee.GetEmployeeResponse)(nil),          // 32: employee_service.requests.employee.get_employee.GetEmployeeResponse
	(*employee.GetEmployeesResponse)(nil),         // 33: employee_service.requests.employee.get_employees.GetEmployeesResponse
	(*employee.CreateEmployeeResponse)(nil),       // 34: employee_service.requests.employee.create_employee.CreateEmployeeResponse
	(*employee.UpdateEmployeeResponse)(nil),       // 35: employee_service.requests.employee.update_employee.UpdateEmployeeResponse
	(*device.GetDeviceResponse)(nil),              // 36: employee_service.requests.device.get_device.GetDeviceResponse
	(*device.GetDevicesResponse)(nil),             // 37: employee_service.requests.device.get_devices.GetDevicesResponse
	(*device.CreateDeviceResponse)(nil),           // 38: employee_service.requests.device.create_device.CreateDeviceResponse
	(*device.UpdateDeviceResponse)(nil),           // 39: employee_service.requests.device.update_device.UpdateDeviceResponse
	(*device.GenerateActivationCodeResponse)(nil), // 40: employee_service.requests.device.generate_activation_code.GenerateActivationCodeResponse
	(*device.ActivateDeviceResponse)(nil),         // 41: employee_service.requests.device.activate_device.ActivateDeviceResponse
	(*device.RefreshDeviceTokenResponse)(nil),     // 42: employee_service.requests.device.refresh_device_token.RefreshDeviceTokenResponse
}
var file_employee_service_employee_service_proto_depIdxs = []int32{
	0,  // 0: employee_service.EmployeeService.GetAction:input_type -> employee_service.requests.action.get_action.GetActionRequest
	1,  // 1: employee_service.EmployeeService.GetActions:input_type -> employee_service.requests.action.get_actions.GetActionsRequest
	2,  // 2: employee_service.EmployeeService.CreateAction:input_type -> employee_service.requests.action.create_action.CreateActionRequest
	3,  // 3: employee_service.EmployeeService.UpdateAction:input_type -> employee_service.requests.action.update_action.UpdateActionRequest
	4,  // 4: employee_service.EmployeeService.DeleteAction:input_type -> employee_service.requests.action.delete_action.DeleteActionRequest
	5,  // 5: employee_service.EmployeeService.GetFacility:input_type -> employee_service.requests.facility.get_facility.GetFacilityRequest
	6,  // 6: employee_service.EmployeeService.GetFacilities:input_type -> employee_service.requests.facility.get_facilities.GetFacilitiesRequest
	7,  // 7: employee_service.EmployeeService.CreateFacility:input_type -> employee_service.requests.facility.create_facility.CreateFacilityRequest
	8,  // 8: employee_service.EmployeeService.UpdateFacility:input_type -> employee_service.requests.facility.update_facility.UpdateFacilityRequest
	9,  // 9: employee_service.EmployeeService.DeleteFacility:input_type -> employee_service.requests.facility.delete_facility.DeleteFacilityRequest
	10, // 10: employee_service.EmployeeService.GetEmployee:input_type -> employee_service.requests.employee.get_employee.GetEmployeeRequest
	11, // 11: employee_service.EmployeeService.GetEmployees:input_type -> employee_service.requests.employee.get_employees.GetEmployeesRequest
	12, // 12: employee_service.EmployeeService.CreateEmployee:input_type -> employee_service.requests.employee.create_employee.CreateEmployeeRequest
	13, // 13: employee_service.EmployeeService.UpdateEmployee:input_type -> employee_service.requests.employee.update_employee.UpdateEmployeeRequest
	14, // 14: employee_service.EmployeeService.DeleteEmployee:input_type -> employee_service.requests.employee.delete_employee.DeleteEmployeeRequest
	15, // 15: employee_service.EmployeeService.GetDevice:input_type -> employee_service.requests.device.get_device.GetDeviceRequest
	16, // 16: employee_service.EmployeeService.GetDevices:input_type -> employee_service.requests.device.get_devices.GetDevicesRequest
	17, // 17: employee_service.EmployeeService.CreateDevice:input_type -> employee_service.requests.device.create_device.CreateDeviceRequest
	18, // 18: employee_service.EmployeeService.UpdateDevice:input_type -> employee_service.requests.device.update_device.UpdateDeviceRequest
	19, // 19: employee_service.EmployeeService.DeleteDevice:input_type -> employee_service.requests.device.delete_device.DeleteDeviceRequest
	20, // 20: employee_service.EmployeeService.GenerateActivationCode:input_type -> employee_service.requests.device.generate_activation_code.GenerateActivationCodeRequest
	21, // 21: employee_service.EmployeeService.ActivateDevice:input_type -> employee_service.requests.device.activate_device.ActivateDeviceRequest
	22, // 22: employee_service.EmployeeService.RefreshDeviceToken:input_type -> employee_service.requests.device.refresh_device_token.RefreshDeviceTokenRequest
	23, // 23: employee_service.EmployeeService.GetAction:output_type -> employee_service.requests.action.get_action.GetActionResponse
	24, // 24: employee_service.EmployeeService.GetActions:output_type -> employee_service.requests.action.get_actions.GetActionsResponse
	25, // 25: employee_service.EmployeeService.CreateAction:output_type -> employee_service.requests.action.create_action.CreateActionResponse
	26, // 26: employee_service.EmployeeService.UpdateAction:output_type -> employee_service.requests.action.update_action.UpdateActionResponse
	27, // 27: employee_service.EmployeeService.DeleteAction:output_type -> google.protobuf.Empty
	28, // 28: employee_service.EmployeeService.GetFacility:output_type -> employee_service.requests.facility.get_facility.GetFacilityResponse
	29, // 29: employee_service.EmployeeService.GetFacilities:output_type -> employee_service.requests.facility.get_facilities.GetFacilitiesResponse
	30, // 30: employee_service.EmployeeService.CreateFacility:output_type -> employee_service.requests.facility.create_facility.CreateFacilityResponse
	31, // 31: employee_service.EmployeeService.UpdateFacility:output_type -> employee_service.requests.facility.update_facility.UpdateFacilityResponse
	27, // 32: employee_service.EmployeeService.DeleteFacility:output_type -> google.protobuf.Empty
	32, // 33: employee_service.EmployeeService.GetEmployee:output_type -> employee_service.requests.employee.get_employee.GetEmployeeResponse
	33, // 34: employee_service.EmployeeService.GetEmployees:output_type -> employee_service.requests.employee.get_employees.GetEmployeesResponse
	34, // 35: employee_service.EmployeeService.CreateEmployee:output_type -> employee_service.requests.employee.create_employee.CreateEmployeeResponse
	35, // 36: employee_service.EmployeeService.UpdateEmployee:output_type -> employee_service.requests.employee.update_employee.UpdateEmployeeResponse
	27, // 37: employee_service.EmployeeService.DeleteEmployee:output_type -> google.protobuf.Empty
	36, // 38: employee_service.EmployeeService.GetDevice:output_type -> employee_service.requests.device.get_device.GetDeviceResponse
	37, // 39: employee_service.EmployeeService.GetDevices:output_type -> employee_service.requests.device.get_devices.GetDevicesResponse
	38, // 40: employee_service.EmployeeService.CreateDevice:output_type -> employee_service.requests.device.create_device.CreateDeviceResponse
	39, // 41: employee_service.EmployeeService.UpdateDevice:output_type -> employee_service.requests.device.update_device.UpdateDeviceResponse
	27, // 42: employee_service.EmployeeService.DeleteDevice:output_type -> google.protobuf.Empty
	40, // 43: employee_service.EmployeeService.GenerateActivationCode:output_type -> employee_service.requests.device.generate_activation_code.GenerateActivationCodeResponse
	41, // 44: employee_service.EmployeeService.ActivateDevice:output_type -> employee_service.requests.device.activate_device.ActivateDeviceResponse
	42, // 45: employee_service.EmployeeService.RefreshDeviceToken:output_type -> employee_service.requests.device.refresh_device_token.RefreshDeviceTokenResponse
	23, // [23:46] is the sub-list for method output_type
	0,  // [0:23] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_employee_service_employee_service_proto_init() }
func file_employee_service_employee_service_proto_init() {
	if File_employee_service_employee_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_employee_service_proto_rawDesc), len(file_employee_service_employee_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_service_employee_service_proto_goTypes,
		DependencyIndexes: file_employee_service_employee_service_proto_depIdxs,
	}.Build()
	File_employee_service_employee_service_proto = out.File
	file_employee_service_employee_service_proto_goTypes = nil
	file_employee_service_employee_service_proto_depIdxs = nil
}
