// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/employee_service.proto

package employee_service

import (
	action "github.com/nicodanke/gesty-api/shared/proto/employee-service/requests/action"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_employee_service_employee_service_proto protoreflect.FileDescriptor

const file_employee_service_employee_service_proto_rawDesc = "" +
	"\n" +
	"'employee-service/employee_service.proto\x12\x10employee_service\x1a6employee-service/requests/action/rpc_get_actions.proto\x1a5employee-service/requests/action/rpc_get_action.proto\x1a8employee-service/requests/action/rpc_create_action.proto\x1a8employee-service/requests/action/rpc_update_action.proto\x1a8employee-service/requests/action/rpc_delete_action.proto\x1a\x1bgoogle/protobuf/empty.proto2\xd5\x05\n" +
	"\x0fEmployeeService\x12\x8a\x01\n" +
	"\tGetAction\x12=.employee_service.requests.action.get_action.GetActionRequest\x1a>.employee_service.requests.action.get_action.GetActionResponse\x12\x8f\x01\n" +
	"\n" +
	"GetActions\x12?.employee_service.requests.action.get_actions.GetActionsRequest\x1a@.employee_service.requests.action.get_actions.GetActionsResponse\x12\x99\x01\n" +
	"\fCreateAction\x12C.employee_service.requests.action.create_action.CreateActionRequest\x1aD.employee_service.requests.action.create_action.CreateActionResponse\x12\x99\x01\n" +
	"\fUpdateAction\x12C.employee_service.requests.action.update_action.UpdateActionRequest\x1aD.employee_service.requests.action.update_action.UpdateActionResponse\x12k\n" +
	"\fDeleteAction\x12C.employee_service.requests.action.delete_action.DeleteActionRequest\x1a\x16.google.protobuf.EmptyB>Z<github.com/nicodanke/gesty-api/shared/proto/employee-serviceb\x06proto3"

var file_employee_service_employee_service_proto_goTypes = []any{
	(*action.GetActionRequest)(nil),     // 0: employee_service.requests.action.get_action.GetActionRequest
	(*action.GetActionsRequest)(nil),    // 1: employee_service.requests.action.get_actions.GetActionsRequest
	(*action.CreateActionRequest)(nil),  // 2: employee_service.requests.action.create_action.CreateActionRequest
	(*action.UpdateActionRequest)(nil),  // 3: employee_service.requests.action.update_action.UpdateActionRequest
	(*action.DeleteActionRequest)(nil),  // 4: employee_service.requests.action.delete_action.DeleteActionRequest
	(*action.GetActionResponse)(nil),    // 5: employee_service.requests.action.get_action.GetActionResponse
	(*action.GetActionsResponse)(nil),   // 6: employee_service.requests.action.get_actions.GetActionsResponse
	(*action.CreateActionResponse)(nil), // 7: employee_service.requests.action.create_action.CreateActionResponse
	(*action.UpdateActionResponse)(nil), // 8: employee_service.requests.action.update_action.UpdateActionResponse
	(*emptypb.Empty)(nil),               // 9: google.protobuf.Empty
}
var file_employee_service_employee_service_proto_depIdxs = []int32{
	0, // 0: employee_service.EmployeeService.GetAction:input_type -> employee_service.requests.action.get_action.GetActionRequest
	1, // 1: employee_service.EmployeeService.GetActions:input_type -> employee_service.requests.action.get_actions.GetActionsRequest
	2, // 2: employee_service.EmployeeService.CreateAction:input_type -> employee_service.requests.action.create_action.CreateActionRequest
	3, // 3: employee_service.EmployeeService.UpdateAction:input_type -> employee_service.requests.action.update_action.UpdateActionRequest
	4, // 4: employee_service.EmployeeService.DeleteAction:input_type -> employee_service.requests.action.delete_action.DeleteActionRequest
	5, // 5: employee_service.EmployeeService.GetAction:output_type -> employee_service.requests.action.get_action.GetActionResponse
	6, // 6: employee_service.EmployeeService.GetActions:output_type -> employee_service.requests.action.get_actions.GetActionsResponse
	7, // 7: employee_service.EmployeeService.CreateAction:output_type -> employee_service.requests.action.create_action.CreateActionResponse
	8, // 8: employee_service.EmployeeService.UpdateAction:output_type -> employee_service.requests.action.update_action.UpdateActionResponse
	9, // 9: employee_service.EmployeeService.DeleteAction:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_employee_service_employee_service_proto_init() }
func file_employee_service_employee_service_proto_init() {
	if File_employee_service_employee_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_employee_service_proto_rawDesc), len(file_employee_service_employee_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_service_employee_service_proto_goTypes,
		DependencyIndexes: file_employee_service_employee_service_proto_depIdxs,
	}.Build()
	File_employee_service_employee_service_proto = out.File
	file_employee_service_employee_service_proto_goTypes = nil
	file_employee_service_employee_service_proto_depIdxs = nil
}
