// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Enabled      bool        `json:"enabled"`
	CanBeDeleted bool        `json:"can_be_deleted"`
	AccountID    int64       `json:"account_id"`
}

type Attendance struct {
	ID         uuid.UUID `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	TimeIn     time.Time `json:"time_in"`
	EmployeeID int64     `json:"employee_id"`
	ActionID   int64     `json:"action_id"`
	DeviceID   int64     `json:"device_id"`
	Precision  float64   `json:"precision"`
}

type Device struct {
	ID                      int64         `json:"id"`
	Name                    string        `json:"name"`
	Password                string        `json:"password"`
	Enabled                 bool          `json:"enabled"`
	Active                  bool          `json:"active"`
	ActivationCode          pgtype.Text   `json:"activation_code"`
	ActivationCodeExpiresAt time.Time     `json:"activation_code_expires_at"`
	DeviceName              pgtype.Text   `json:"device_name"`
	DeviceModel             pgtype.Text   `json:"device_model"`
	DeviceBrand             pgtype.Text   `json:"device_brand"`
	DeviceSerialNumber      pgtype.Text   `json:"device_serial_number"`
	DeviceOs                pgtype.Text   `json:"device_os"`
	DeviceRam               pgtype.Float8 `json:"device_ram"`
	DeviceStorage           pgtype.Float8 `json:"device_storage"`
	DeviceOsVersion         pgtype.Text   `json:"device_os_version"`
	FacilityID              int64         `json:"facility_id"`
	AccountID               int64         `json:"account_id"`
	CreatedAt               time.Time     `json:"created_at"`
	UpdatedAt               time.Time     `json:"updated_at"`
}

type DeviceAction struct {
	DeviceID int64 `json:"device_id"`
	ActionID int64 `json:"action_id"`
}

type DeviceHealth struct {
	ID              int64         `json:"id"`
	ConnectionType  string        `json:"connection_type"`
	FreeMemory      pgtype.Float8 `json:"free_memory"`
	FreeStorage     pgtype.Float8 `json:"free_storage"`
	BatteryLevel    pgtype.Float8 `json:"battery_level"`
	BatterySaveMode bool          `json:"battery_save_mode"`
	CreatedAt       time.Time     `json:"created_at"`
	DeviceID        int64         `json:"device_id"`
}

type Employee struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Lastname  string    `json:"lastname"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Gender    string    `json:"gender"`
	RealID    string    `json:"real_id"`
	FiscalID  string    `json:"fiscal_id"`
	AccountID int64     `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type EmployeeAddress struct {
	EmployeeID int64         `json:"employee_id"`
	Country    string        `json:"country"`
	State      string        `json:"state"`
	SubState   pgtype.Text   `json:"sub_state"`
	Street     string        `json:"street"`
	Number     string        `json:"number"`
	Unit       pgtype.Text   `json:"unit"`
	ZipCode    string        `json:"zip_code"`
	Lat        pgtype.Float8 `json:"lat"`
	Lng        pgtype.Float8 `json:"lng"`
}

type EmployeeFacility struct {
	FacilityID int64 `json:"facility_id"`
	EmployeeID int64 `json:"employee_id"`
}

type EmployeePhoto struct {
	ID          int64     `json:"id"`
	EmployeeID  int64     `json:"employee_id"`
	AccountID   int64     `json:"account_id"`
	ImageBase64 string    `json:"image_base_64"`
	VectorImage string    `json:"vector_image"`
	IsProfile   bool      `json:"is_profile"`
	CreatedAt   time.Time `json:"created_at"`
}

type Facility struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	OpenTime    pgtype.Time `json:"open_time"`
	CloseTime   pgtype.Time `json:"close_time"`
	AccountID   int64       `json:"account_id"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type FacilityAddress struct {
	FacilityID int64         `json:"facility_id"`
	Country    string        `json:"country"`
	State      string        `json:"state"`
	SubState   pgtype.Text   `json:"sub_state"`
	Street     string        `json:"street"`
	Number     string        `json:"number"`
	Unit       pgtype.Text   `json:"unit"`
	ZipCode    string        `json:"zip_code"`
	Lat        pgtype.Float8 `json:"lat"`
	Lng        pgtype.Float8 `json:"lng"`
}
