// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: account-service/requests/user/rpc_get_users.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	models "shared/proto/account-service/models"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *int32                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_account_service_requests_user_rpc_get_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_user_rpc_get_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_account_service_requests_user_rpc_get_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetUsersRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*models.User         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_account_service_requests_user_rpc_get_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_user_rpc_get_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_account_service_requests_user_rpc_get_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersResponse) GetUsers() []*models.User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_account_service_requests_user_rpc_get_users_proto protoreflect.FileDescriptor

const file_account_service_requests_user_rpc_get_users_proto_rawDesc = "" +
	"\n" +
	"1account-service/requests/user/rpc_get_users.proto\x12'account_service.requests.user.get_users\x1a!account-service/models/user.proto\"U\n" +
	"\x0fGetUsersRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x05H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size\"K\n" +
	"\x10GetUsersResponse\x127\n" +
	"\x05users\x18\x01 \x03(\v2!.account_service.models.user.UserR\x05usersB,Z*shared/proto/account-service/requests/userb\x06proto3"

var (
	file_account_service_requests_user_rpc_get_users_proto_rawDescOnce sync.Once
	file_account_service_requests_user_rpc_get_users_proto_rawDescData []byte
)

func file_account_service_requests_user_rpc_get_users_proto_rawDescGZIP() []byte {
	file_account_service_requests_user_rpc_get_users_proto_rawDescOnce.Do(func() {
		file_account_service_requests_user_rpc_get_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_requests_user_rpc_get_users_proto_rawDesc), len(file_account_service_requests_user_rpc_get_users_proto_rawDesc)))
	})
	return file_account_service_requests_user_rpc_get_users_proto_rawDescData
}

var file_account_service_requests_user_rpc_get_users_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_service_requests_user_rpc_get_users_proto_goTypes = []any{
	(*GetUsersRequest)(nil),  // 0: account_service.requests.user.get_users.GetUsersRequest
	(*GetUsersResponse)(nil), // 1: account_service.requests.user.get_users.GetUsersResponse
	(*models.User)(nil),      // 2: account_service.models.user.User
}
var file_account_service_requests_user_rpc_get_users_proto_depIdxs = []int32{
	2, // 0: account_service.requests.user.get_users.GetUsersResponse.users:type_name -> account_service.models.user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_service_requests_user_rpc_get_users_proto_init() }
func file_account_service_requests_user_rpc_get_users_proto_init() {
	if File_account_service_requests_user_rpc_get_users_proto != nil {
		return
	}
	file_account_service_requests_user_rpc_get_users_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_requests_user_rpc_get_users_proto_rawDesc), len(file_account_service_requests_user_rpc_get_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_service_requests_user_rpc_get_users_proto_goTypes,
		DependencyIndexes: file_account_service_requests_user_rpc_get_users_proto_depIdxs,
		MessageInfos:      file_account_service_requests_user_rpc_get_users_proto_msgTypes,
	}.Build()
	File_account_service_requests_user_rpc_get_users_proto = out.File
	file_account_service_requests_user_rpc_get_users_proto_goTypes = nil
	file_account_service_requests_user_rpc_get_users_proto_depIdxs = nil
}
