// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: account-service/requests/user/rpc_create_user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	models "shared/proto/account-service/models"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	RoleId        int64                  `protobuf:"varint,6,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Phone         *string                `protobuf:"bytes,7,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Active        *bool                  `protobuf:"varint,8,opt,name=active,proto3,oneof" json:"active,omitempty"`
	IsAdmin       *bool                  `protobuf:"varint,9,opt,name=isAdmin,proto3,oneof" json:"isAdmin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_account_service_requests_user_rpc_create_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_user_rpc_create_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_account_service_requests_user_rpc_create_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *CreateUserRequest) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_account_service_requests_user_rpc_create_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_user_rpc_create_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_account_service_requests_user_rpc_create_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_account_service_requests_user_rpc_create_user_proto protoreflect.FileDescriptor

const file_account_service_requests_user_rpc_create_user_proto_rawDesc = "" +
	"\n" +
	"3account-service/requests/user/rpc_create_user.proto\x12)account_service.requests.user.create_user\x1a!account-service/models/user.proto\"\xa1\x02\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x16\n" +
	"\x06roleId\x18\x06 \x01(\x03R\x06roleId\x12\x19\n" +
	"\x05phone\x18\a \x01(\tH\x00R\x05phone\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\b \x01(\bH\x01R\x06active\x88\x01\x01\x12\x1d\n" +
	"\aisAdmin\x18\t \x01(\bH\x02R\aisAdmin\x88\x01\x01B\b\n" +
	"\x06_phoneB\t\n" +
	"\a_activeB\n" +
	"\n" +
	"\b_isAdmin\"K\n" +
	"\x12CreateUserResponse\x125\n" +
	"\x04user\x18\x01 \x01(\v2!.account_service.models.user.UserR\x04userB,Z*shared/proto/account-service/requests/userb\x06proto3"

var (
	file_account_service_requests_user_rpc_create_user_proto_rawDescOnce sync.Once
	file_account_service_requests_user_rpc_create_user_proto_rawDescData []byte
)

func file_account_service_requests_user_rpc_create_user_proto_rawDescGZIP() []byte {
	file_account_service_requests_user_rpc_create_user_proto_rawDescOnce.Do(func() {
		file_account_service_requests_user_rpc_create_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_requests_user_rpc_create_user_proto_rawDesc), len(file_account_service_requests_user_rpc_create_user_proto_rawDesc)))
	})
	return file_account_service_requests_user_rpc_create_user_proto_rawDescData
}

var file_account_service_requests_user_rpc_create_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_service_requests_user_rpc_create_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: account_service.requests.user.create_user.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: account_service.requests.user.create_user.CreateUserResponse
	(*models.User)(nil),        // 2: account_service.models.user.User
}
var file_account_service_requests_user_rpc_create_user_proto_depIdxs = []int32{
	2, // 0: account_service.requests.user.create_user.CreateUserResponse.user:type_name -> account_service.models.user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_service_requests_user_rpc_create_user_proto_init() }
func file_account_service_requests_user_rpc_create_user_proto_init() {
	if File_account_service_requests_user_rpc_create_user_proto != nil {
		return
	}
	file_account_service_requests_user_rpc_create_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_requests_user_rpc_create_user_proto_rawDesc), len(file_account_service_requests_user_rpc_create_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_service_requests_user_rpc_create_user_proto_goTypes,
		DependencyIndexes: file_account_service_requests_user_rpc_create_user_proto_depIdxs,
		MessageInfos:      file_account_service_requests_user_rpc_create_user_proto_msgTypes,
	}.Build()
	File_account_service_requests_user_rpc_create_user_proto = out.File
	file_account_service_requests_user_rpc_create_user_proto_goTypes = nil
	file_account_service_requests_user_rpc_create_user_proto_depIdxs = nil
}
