// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: account-service/requests/user/rpc_update_user.proto

package user

import (
	models "github.com/nicodanke/gesty-api/shared/proto/account-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Lastname      *string                `protobuf:"bytes,3,opt,name=lastname,proto3,oneof" json:"lastname,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	RoleId        *int64                 `protobuf:"varint,5,opt,name=roleId,proto3,oneof" json:"roleId,omitempty"`
	Phone         *string                `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Active        *bool                  `protobuf:"varint,7,opt,name=active,proto3,oneof" json:"active,omitempty"`
	IsAdmin       *bool                  `protobuf:"varint,8,opt,name=isAdmin,proto3,oneof" json:"isAdmin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_account_service_requests_user_rpc_update_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_user_rpc_update_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_account_service_requests_user_rpc_update_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetLastname() string {
	if x != nil && x.Lastname != nil {
		return *x.Lastname
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetRoleId() int64 {
	if x != nil && x.RoleId != nil {
		return *x.RoleId
	}
	return 0
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *UpdateUserRequest) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_account_service_requests_user_rpc_update_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_user_rpc_update_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_account_service_requests_user_rpc_update_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_account_service_requests_user_rpc_update_user_proto protoreflect.FileDescriptor

const file_account_service_requests_user_rpc_update_user_proto_rawDesc = "" +
	"\n" +
	"3account-service/requests/user/rpc_update_user.proto\x12)account_service.requests.user.update_user\x1a!account-service/models/user.proto\"\xb8\x02\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\blastname\x18\x03 \x01(\tH\x01R\blastname\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x1b\n" +
	"\x06roleId\x18\x05 \x01(\x03H\x03R\x06roleId\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x04R\x05phone\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\a \x01(\bH\x05R\x06active\x88\x01\x01\x12\x1d\n" +
	"\aisAdmin\x18\b \x01(\bH\x06R\aisAdmin\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_lastnameB\b\n" +
	"\x06_emailB\t\n" +
	"\a_roleIdB\b\n" +
	"\x06_phoneB\t\n" +
	"\a_activeB\n" +
	"\n" +
	"\b_isAdmin\"K\n" +
	"\x12UpdateUserResponse\x125\n" +
	"\x04user\x18\x01 \x01(\v2!.account_service.models.user.UserR\x04userBKZIgithub.com/nicodanke/gesty-api/shared/proto/account-service/requests/userb\x06proto3"

var (
	file_account_service_requests_user_rpc_update_user_proto_rawDescOnce sync.Once
	file_account_service_requests_user_rpc_update_user_proto_rawDescData []byte
)

func file_account_service_requests_user_rpc_update_user_proto_rawDescGZIP() []byte {
	file_account_service_requests_user_rpc_update_user_proto_rawDescOnce.Do(func() {
		file_account_service_requests_user_rpc_update_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_requests_user_rpc_update_user_proto_rawDesc), len(file_account_service_requests_user_rpc_update_user_proto_rawDesc)))
	})
	return file_account_service_requests_user_rpc_update_user_proto_rawDescData
}

var file_account_service_requests_user_rpc_update_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_service_requests_user_rpc_update_user_proto_goTypes = []any{
	(*UpdateUserRequest)(nil),  // 0: account_service.requests.user.update_user.UpdateUserRequest
	(*UpdateUserResponse)(nil), // 1: account_service.requests.user.update_user.UpdateUserResponse
	(*models.User)(nil),        // 2: account_service.models.user.User
}
var file_account_service_requests_user_rpc_update_user_proto_depIdxs = []int32{
	2, // 0: account_service.requests.user.update_user.UpdateUserResponse.user:type_name -> account_service.models.user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_service_requests_user_rpc_update_user_proto_init() }
func file_account_service_requests_user_rpc_update_user_proto_init() {
	if File_account_service_requests_user_rpc_update_user_proto != nil {
		return
	}
	file_account_service_requests_user_rpc_update_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_requests_user_rpc_update_user_proto_rawDesc), len(file_account_service_requests_user_rpc_update_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_service_requests_user_rpc_update_user_proto_goTypes,
		DependencyIndexes: file_account_service_requests_user_rpc_update_user_proto_depIdxs,
		MessageInfos:      file_account_service_requests_user_rpc_update_user_proto_msgTypes,
	}.Build()
	File_account_service_requests_user_rpc_update_user_proto = out.File
	file_account_service_requests_user_rpc_update_user_proto_goTypes = nil
	file_account_service_requests_user_rpc_update_user_proto_depIdxs = nil
}
