DROP TABLE IF EXISTS "session";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "role_permission";
DROP TABLE IF EXISTS "role";
DROP TABLE IF EXISTS "permission";
DROP TABLE IF EXISTS "account_module";
DROP TABLE IF EXISTS "module";
DROP TABLE IF EXISTS "account_address";
DROP TABLE IF EXISTS "account";
