// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: account-service/requests/account/rpc_account_me.proto

package account

import (
	models "github.com/nicodanke/gesty-api/shared/proto/account-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *models.Account        `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountMeResponse) Reset() {
	*x = AccountMeResponse{}
	mi := &file_account_service_requests_account_rpc_account_me_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMeResponse) ProtoMessage() {}

func (x *AccountMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_account_rpc_account_me_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMeResponse.ProtoReflect.Descriptor instead.
func (*AccountMeResponse) Descriptor() ([]byte, []int) {
	return file_account_service_requests_account_rpc_account_me_proto_rawDescGZIP(), []int{0}
}

func (x *AccountMeResponse) GetAccount() *models.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_account_service_requests_account_rpc_account_me_proto protoreflect.FileDescriptor

const file_account_service_requests_account_rpc_account_me_proto_rawDesc = "" +
	"\n" +
	"5account-service/requests/account/rpc_account_me.proto\x12+account_service.requests.account.account_me\x1a$account-service/models/account.proto\"V\n" +
	"\x11AccountMeResponse\x12A\n" +
	"\aaccount\x18\x01 \x01(\v2'.account_service.models.account.AccountR\aaccountBNZLgithub.com/nicodanke/gesty-api/shared/proto/account-service/requests/accountb\x06proto3"

var (
	file_account_service_requests_account_rpc_account_me_proto_rawDescOnce sync.Once
	file_account_service_requests_account_rpc_account_me_proto_rawDescData []byte
)

func file_account_service_requests_account_rpc_account_me_proto_rawDescGZIP() []byte {
	file_account_service_requests_account_rpc_account_me_proto_rawDescOnce.Do(func() {
		file_account_service_requests_account_rpc_account_me_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_requests_account_rpc_account_me_proto_rawDesc), len(file_account_service_requests_account_rpc_account_me_proto_rawDesc)))
	})
	return file_account_service_requests_account_rpc_account_me_proto_rawDescData
}

var file_account_service_requests_account_rpc_account_me_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_account_service_requests_account_rpc_account_me_proto_goTypes = []any{
	(*AccountMeResponse)(nil), // 0: account_service.requests.account.account_me.AccountMeResponse
	(*models.Account)(nil),    // 1: account_service.models.account.Account
}
var file_account_service_requests_account_rpc_account_me_proto_depIdxs = []int32{
	1, // 0: account_service.requests.account.account_me.AccountMeResponse.account:type_name -> account_service.models.account.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_service_requests_account_rpc_account_me_proto_init() }
func file_account_service_requests_account_rpc_account_me_proto_init() {
	if File_account_service_requests_account_rpc_account_me_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_requests_account_rpc_account_me_proto_rawDesc), len(file_account_service_requests_account_rpc_account_me_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_service_requests_account_rpc_account_me_proto_goTypes,
		DependencyIndexes: file_account_service_requests_account_rpc_account_me_proto_depIdxs,
		MessageInfos:      file_account_service_requests_account_rpc_account_me_proto_msgTypes,
	}.Build()
	File_account_service_requests_account_rpc_account_me_proto = out.File
	file_account_service_requests_account_rpc_account_me_proto_goTypes = nil
	file_account_service_requests_account_rpc_account_me_proto_depIdxs = nil
}
