// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteRolePermissions(ctx context.Context, roleID int64) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountByCode(ctx context.Context, code string) (Account, error)
	GetAccountModules(ctx context.Context, accountID int64) ([]string, error)
	GetRole(ctx context.Context, arg GetRoleParams) (GetRoleRow, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]GetRolesRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPermissions(ctx context.Context, id int64) ([]string, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
