// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/employee/rpc_get_employees.proto

package employee

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *int32                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeesRequest) Reset() {
	*x = GetEmployeesRequest{}
	mi := &file_employee_service_requests_employee_rpc_get_employees_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeesRequest) ProtoMessage() {}

func (x *GetEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_employee_rpc_get_employees_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_employee_rpc_get_employees_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmployeesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetEmployeesRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*models.Employee     `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeesResponse) Reset() {
	*x = GetEmployeesResponse{}
	mi := &file_employee_service_requests_employee_rpc_get_employees_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeesResponse) ProtoMessage() {}

func (x *GetEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_employee_rpc_get_employees_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_employee_rpc_get_employees_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmployeesResponse) GetEmployees() []*models.Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

var File_employee_service_requests_employee_rpc_get_employees_proto protoreflect.FileDescriptor

const file_employee_service_requests_employee_rpc_get_employees_proto_rawDesc = "" +
	"\n" +
	":employee-service/requests/employee/rpc_get_employees.proto\x120employee_service.requests.employee.get_employees\x1a&employee-service/models/employee.proto\"Y\n" +
	"\x13GetEmployeesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x05H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size\"`\n" +
	"\x14GetEmployeesResponse\x12H\n" +
	"\temployees\x18\x01 \x03(\v2*.employee_service.models.employee.EmployeeR\temployeesBPZNgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/employeeb\x06proto3"

var (
	file_employee_service_requests_employee_rpc_get_employees_proto_rawDescOnce sync.Once
	file_employee_service_requests_employee_rpc_get_employees_proto_rawDescData []byte
)

func file_employee_service_requests_employee_rpc_get_employees_proto_rawDescGZIP() []byte {
	file_employee_service_requests_employee_rpc_get_employees_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_employee_rpc_get_employees_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_employee_rpc_get_employees_proto_rawDesc), len(file_employee_service_requests_employee_rpc_get_employees_proto_rawDesc)))
	})
	return file_employee_service_requests_employee_rpc_get_employees_proto_rawDescData
}

var file_employee_service_requests_employee_rpc_get_employees_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_employee_rpc_get_employees_proto_goTypes = []any{
	(*GetEmployeesRequest)(nil),  // 0: employee_service.requests.employee.get_employees.GetEmployeesRequest
	(*GetEmployeesResponse)(nil), // 1: employee_service.requests.employee.get_employees.GetEmployeesResponse
	(*models.Employee)(nil),      // 2: employee_service.models.employee.Employee
}
var file_employee_service_requests_employee_rpc_get_employees_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.employee.get_employees.GetEmployeesResponse.employees:type_name -> employee_service.models.employee.Employee
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_employee_rpc_get_employees_proto_init() }
func file_employee_service_requests_employee_rpc_get_employees_proto_init() {
	if File_employee_service_requests_employee_rpc_get_employees_proto != nil {
		return
	}
	file_employee_service_requests_employee_rpc_get_employees_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_employee_rpc_get_employees_proto_rawDesc), len(file_employee_service_requests_employee_rpc_get_employees_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_employee_rpc_get_employees_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_employee_rpc_get_employees_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_employee_rpc_get_employees_proto_msgTypes,
	}.Build()
	File_employee_service_requests_employee_rpc_get_employees_proto = out.File
	file_employee_service_requests_employee_rpc_get_employees_proto_goTypes = nil
	file_employee_service_requests_employee_rpc_get_employees_proto_depIdxs = nil
}
