// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/employee/rpc_get_employee.proto

package employee

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_employee_service_requests_employee_rpc_get_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_employee_rpc_get_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_employee_rpc_get_employee_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmployeeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *models.Employee       `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeResponse) Reset() {
	*x = GetEmployeeResponse{}
	mi := &file_employee_service_requests_employee_rpc_get_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeResponse) ProtoMessage() {}

func (x *GetEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_employee_rpc_get_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_employee_rpc_get_employee_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmployeeResponse) GetEmployee() *models.Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

var File_employee_service_requests_employee_rpc_get_employee_proto protoreflect.FileDescriptor

const file_employee_service_requests_employee_rpc_get_employee_proto_rawDesc = "" +
	"\n" +
	"9employee-service/requests/employee/rpc_get_employee.proto\x12/employee_service.requests.employee.get_employee\x1a&employee-service/models/employee.proto\"$\n" +
	"\x12GetEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"]\n" +
	"\x13GetEmployeeResponse\x12F\n" +
	"\bemployee\x18\x01 \x01(\v2*.employee_service.models.employee.EmployeeR\bemployeeBPZNgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/employeeb\x06proto3"

var (
	file_employee_service_requests_employee_rpc_get_employee_proto_rawDescOnce sync.Once
	file_employee_service_requests_employee_rpc_get_employee_proto_rawDescData []byte
)

func file_employee_service_requests_employee_rpc_get_employee_proto_rawDescGZIP() []byte {
	file_employee_service_requests_employee_rpc_get_employee_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_employee_rpc_get_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_employee_rpc_get_employee_proto_rawDesc), len(file_employee_service_requests_employee_rpc_get_employee_proto_rawDesc)))
	})
	return file_employee_service_requests_employee_rpc_get_employee_proto_rawDescData
}

var file_employee_service_requests_employee_rpc_get_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_employee_rpc_get_employee_proto_goTypes = []any{
	(*GetEmployeeRequest)(nil),  // 0: employee_service.requests.employee.get_employee.GetEmployeeRequest
	(*GetEmployeeResponse)(nil), // 1: employee_service.requests.employee.get_employee.GetEmployeeResponse
	(*models.Employee)(nil),     // 2: employee_service.models.employee.Employee
}
var file_employee_service_requests_employee_rpc_get_employee_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.employee.get_employee.GetEmployeeResponse.employee:type_name -> employee_service.models.employee.Employee
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_employee_rpc_get_employee_proto_init() }
func file_employee_service_requests_employee_rpc_get_employee_proto_init() {
	if File_employee_service_requests_employee_rpc_get_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_employee_rpc_get_employee_proto_rawDesc), len(file_employee_service_requests_employee_rpc_get_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_employee_rpc_get_employee_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_employee_rpc_get_employee_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_employee_rpc_get_employee_proto_msgTypes,
	}.Build()
	File_employee_service_requests_employee_rpc_get_employee_proto = out.File
	file_employee_service_requests_employee_rpc_get_employee_proto_goTypes = nil
	file_employee_service_requests_employee_rpc_get_employee_proto_depIdxs = nil
}
