// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: account-service/requests/role/rpc_create_role.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	models "shared/proto/account-service/models"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_account_service_requests_role_rpc_create_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_role_rpc_create_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_account_service_requests_role_rpc_create_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *models.Role           `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_account_service_requests_role_rpc_create_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_requests_role_rpc_create_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_account_service_requests_role_rpc_create_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleResponse) GetRole() *models.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

var File_account_service_requests_role_rpc_create_role_proto protoreflect.FileDescriptor

const file_account_service_requests_role_rpc_create_role_proto_rawDesc = "" +
	"\n" +
	"3account-service/requests/role/rpc_create_role.proto\x12)account_service.requests.role.create_role\x1a!account-service/models/role.proto\"'\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x12CreateRoleResponse\x125\n" +
	"\x04role\x18\x01 \x01(\v2!.account_service.models.role.RoleR\x04roleB,Z*shared/proto/account-service/requests/roleb\x06proto3"

var (
	file_account_service_requests_role_rpc_create_role_proto_rawDescOnce sync.Once
	file_account_service_requests_role_rpc_create_role_proto_rawDescData []byte
)

func file_account_service_requests_role_rpc_create_role_proto_rawDescGZIP() []byte {
	file_account_service_requests_role_rpc_create_role_proto_rawDescOnce.Do(func() {
		file_account_service_requests_role_rpc_create_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_requests_role_rpc_create_role_proto_rawDesc), len(file_account_service_requests_role_rpc_create_role_proto_rawDesc)))
	})
	return file_account_service_requests_role_rpc_create_role_proto_rawDescData
}

var file_account_service_requests_role_rpc_create_role_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_service_requests_role_rpc_create_role_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),  // 0: account_service.requests.role.create_role.CreateRoleRequest
	(*CreateRoleResponse)(nil), // 1: account_service.requests.role.create_role.CreateRoleResponse
	(*models.Role)(nil),        // 2: account_service.models.role.Role
}
var file_account_service_requests_role_rpc_create_role_proto_depIdxs = []int32{
	2, // 0: account_service.requests.role.create_role.CreateRoleResponse.role:type_name -> account_service.models.role.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_service_requests_role_rpc_create_role_proto_init() }
func file_account_service_requests_role_rpc_create_role_proto_init() {
	if File_account_service_requests_role_rpc_create_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_requests_role_rpc_create_role_proto_rawDesc), len(file_account_service_requests_role_rpc_create_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_service_requests_role_rpc_create_role_proto_goTypes,
		DependencyIndexes: file_account_service_requests_role_rpc_create_role_proto_depIdxs,
		MessageInfos:      file_account_service_requests_role_rpc_create_role_proto_msgTypes,
	}.Build()
	File_account_service_requests_role_rpc_create_role_proto = out.File
	file_account_service_requests_role_rpc_create_role_proto_goTypes = nil
	file_account_service_requests_role_rpc_create_role_proto_depIdxs = nil
}
