// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/device/rpc_get_devices.proto

package device

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *int32                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesRequest) Reset() {
	*x = GetDevicesRequest{}
	mi := &file_employee_service_requests_device_rpc_get_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesRequest) ProtoMessage() {}

func (x *GetDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_get_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_get_devices_proto_rawDescGZIP(), []int{0}
}

func (x *GetDevicesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetDevicesRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*models.Device       `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	mi := &file_employee_service_requests_device_rpc_get_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_get_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_get_devices_proto_rawDescGZIP(), []int{1}
}

func (x *GetDevicesResponse) GetDevices() []*models.Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_employee_service_requests_device_rpc_get_devices_proto protoreflect.FileDescriptor

const file_employee_service_requests_device_rpc_get_devices_proto_rawDesc = "" +
	"\n" +
	"6employee-service/requests/device/rpc_get_devices.proto\x12,employee_service.requests.device.get_devices\x1a$employee-service/models/device.proto\"W\n" +
	"\x11GetDevicesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x05H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size\"V\n" +
	"\x12GetDevicesResponse\x12@\n" +
	"\adevices\x18\x01 \x03(\v2&.employee_service.models.device.DeviceR\adevicesBNZLgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/deviceb\x06proto3"

var (
	file_employee_service_requests_device_rpc_get_devices_proto_rawDescOnce sync.Once
	file_employee_service_requests_device_rpc_get_devices_proto_rawDescData []byte
)

func file_employee_service_requests_device_rpc_get_devices_proto_rawDescGZIP() []byte {
	file_employee_service_requests_device_rpc_get_devices_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_device_rpc_get_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_get_devices_proto_rawDesc), len(file_employee_service_requests_device_rpc_get_devices_proto_rawDesc)))
	})
	return file_employee_service_requests_device_rpc_get_devices_proto_rawDescData
}

var file_employee_service_requests_device_rpc_get_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_device_rpc_get_devices_proto_goTypes = []any{
	(*GetDevicesRequest)(nil),  // 0: employee_service.requests.device.get_devices.GetDevicesRequest
	(*GetDevicesResponse)(nil), // 1: employee_service.requests.device.get_devices.GetDevicesResponse
	(*models.Device)(nil),      // 2: employee_service.models.device.Device
}
var file_employee_service_requests_device_rpc_get_devices_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.device.get_devices.GetDevicesResponse.devices:type_name -> employee_service.models.device.Device
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_device_rpc_get_devices_proto_init() }
func file_employee_service_requests_device_rpc_get_devices_proto_init() {
	if File_employee_service_requests_device_rpc_get_devices_proto != nil {
		return
	}
	file_employee_service_requests_device_rpc_get_devices_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_get_devices_proto_rawDesc), len(file_employee_service_requests_device_rpc_get_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_device_rpc_get_devices_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_device_rpc_get_devices_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_device_rpc_get_devices_proto_msgTypes,
	}.Build()
	File_employee_service_requests_device_rpc_get_devices_proto = out.File
	file_employee_service_requests_device_rpc_get_devices_proto_goTypes = nil
	file_employee_service_requests_device_rpc_get_devices_proto_depIdxs = nil
}
