// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/device/rpc_update_device.proto

package device

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDeviceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Enabled          *bool                  `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	FacilityId       int64                  `protobuf:"varint,4,opt,name=facilityId,proto3" json:"facilityId,omitempty"`
	ActionIds        []int64                `protobuf:"varint,5,rep,packed,name=actionIds,proto3" json:"actionIds,omitempty"`
	RemoveAllActions *bool                  `protobuf:"varint,6,opt,name=removeAllActions,proto3,oneof" json:"removeAllActions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_employee_service_requests_device_rpc_update_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_update_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_update_device_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDeviceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDeviceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateDeviceRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *UpdateDeviceRequest) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *UpdateDeviceRequest) GetActionIds() []int64 {
	if x != nil {
		return x.ActionIds
	}
	return nil
}

func (x *UpdateDeviceRequest) GetRemoveAllActions() bool {
	if x != nil && x.RemoveAllActions != nil {
		return *x.RemoveAllActions
	}
	return false
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *models.Device         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_employee_service_requests_device_rpc_update_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_update_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_update_device_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDeviceResponse) GetDevice() *models.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

var File_employee_service_requests_device_rpc_update_device_proto protoreflect.FileDescriptor

const file_employee_service_requests_device_rpc_update_device_proto_rawDesc = "" +
	"\n" +
	"8employee-service/requests/device/rpc_update_device.proto\x12.employee_service.requests.device.update_device\x1a$employee-service/models/device.proto\"\xf6\x01\n" +
	"\x13UpdateDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x03 \x01(\bH\x01R\aenabled\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"facilityId\x18\x04 \x01(\x03R\n" +
	"facilityId\x12\x1c\n" +
	"\tactionIds\x18\x05 \x03(\x03R\tactionIds\x12/\n" +
	"\x10removeAllActions\x18\x06 \x01(\bH\x02R\x10removeAllActions\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_enabledB\x13\n" +
	"\x11_removeAllActions\"V\n" +
	"\x14UpdateDeviceResponse\x12>\n" +
	"\x06device\x18\x01 \x01(\v2&.employee_service.models.device.DeviceR\x06deviceBNZLgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/deviceb\x06proto3"

var (
	file_employee_service_requests_device_rpc_update_device_proto_rawDescOnce sync.Once
	file_employee_service_requests_device_rpc_update_device_proto_rawDescData []byte
)

func file_employee_service_requests_device_rpc_update_device_proto_rawDescGZIP() []byte {
	file_employee_service_requests_device_rpc_update_device_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_device_rpc_update_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_update_device_proto_rawDesc), len(file_employee_service_requests_device_rpc_update_device_proto_rawDesc)))
	})
	return file_employee_service_requests_device_rpc_update_device_proto_rawDescData
}

var file_employee_service_requests_device_rpc_update_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_device_rpc_update_device_proto_goTypes = []any{
	(*UpdateDeviceRequest)(nil),  // 0: employee_service.requests.device.update_device.UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil), // 1: employee_service.requests.device.update_device.UpdateDeviceResponse
	(*models.Device)(nil),        // 2: employee_service.models.device.Device
}
var file_employee_service_requests_device_rpc_update_device_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.device.update_device.UpdateDeviceResponse.device:type_name -> employee_service.models.device.Device
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_device_rpc_update_device_proto_init() }
func file_employee_service_requests_device_rpc_update_device_proto_init() {
	if File_employee_service_requests_device_rpc_update_device_proto != nil {
		return
	}
	file_employee_service_requests_device_rpc_update_device_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_update_device_proto_rawDesc), len(file_employee_service_requests_device_rpc_update_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_device_rpc_update_device_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_device_rpc_update_device_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_device_rpc_update_device_proto_msgTypes,
	}.Build()
	File_employee_service_requests_device_rpc_update_device_proto = out.File
	file_employee_service_requests_device_rpc_update_device_proto_goTypes = nil
	file_employee_service_requests_device_rpc_update_device_proto_depIdxs = nil
}
