// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/device/rpc_generate_activation_code.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateActivationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateActivationCodeRequest) Reset() {
	*x = GenerateActivationCodeRequest{}
	mi := &file_employee_service_requests_device_rpc_generate_activation_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateActivationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateActivationCodeRequest) ProtoMessage() {}

func (x *GenerateActivationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_generate_activation_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateActivationCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateActivationCodeRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateActivationCodeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GenerateActivationCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateActivationCodeResponse) Reset() {
	*x = GenerateActivationCodeResponse{}
	mi := &file_employee_service_requests_device_rpc_generate_activation_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateActivationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateActivationCodeResponse) ProtoMessage() {}

func (x *GenerateActivationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_generate_activation_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateActivationCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateActivationCodeResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateActivationCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_employee_service_requests_device_rpc_generate_activation_code_proto protoreflect.FileDescriptor

const file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDesc = "" +
	"\n" +
	"Cemployee-service/requests/device/rpc_generate_activation_code.proto\x129employee_service.requests.device.generate_activation_code\"/\n" +
	"\x1dGenerateActivationCodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x1eGenerateActivationCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04codeBNZLgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/deviceb\x06proto3"

var (
	file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescOnce sync.Once
	file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescData []byte
)

func file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescGZIP() []byte {
	file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDesc), len(file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDesc)))
	})
	return file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDescData
}

var file_employee_service_requests_device_rpc_generate_activation_code_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_device_rpc_generate_activation_code_proto_goTypes = []any{
	(*GenerateActivationCodeRequest)(nil),  // 0: employee_service.requests.device.generate_activation_code.GenerateActivationCodeRequest
	(*GenerateActivationCodeResponse)(nil), // 1: employee_service.requests.device.generate_activation_code.GenerateActivationCodeResponse
}
var file_employee_service_requests_device_rpc_generate_activation_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_employee_service_requests_device_rpc_generate_activation_code_proto_init() }
func file_employee_service_requests_device_rpc_generate_activation_code_proto_init() {
	if File_employee_service_requests_device_rpc_generate_activation_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDesc), len(file_employee_service_requests_device_rpc_generate_activation_code_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_device_rpc_generate_activation_code_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_device_rpc_generate_activation_code_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_device_rpc_generate_activation_code_proto_msgTypes,
	}.Build()
	File_employee_service_requests_device_rpc_generate_activation_code_proto = out.File
	file_employee_service_requests_device_rpc_generate_activation_code_proto_goTypes = nil
	file_employee_service_requests_device_rpc_generate_activation_code_proto_depIdxs = nil
}
