// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/device/rpc_get_device.proto

package device

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_employee_service_requests_device_rpc_get_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_get_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_get_device_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *models.Device         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_employee_service_requests_device_rpc_get_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_device_rpc_get_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_device_rpc_get_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeviceResponse) GetDevice() *models.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

var File_employee_service_requests_device_rpc_get_device_proto protoreflect.FileDescriptor

const file_employee_service_requests_device_rpc_get_device_proto_rawDesc = "" +
	"\n" +
	"5employee-service/requests/device/rpc_get_device.proto\x12+employee_service.requests.device.get_device\x1a$employee-service/models/device.proto\"\"\n" +
	"\x10GetDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\x11GetDeviceResponse\x12>\n" +
	"\x06device\x18\x01 \x01(\v2&.employee_service.models.device.DeviceR\x06deviceBNZLgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/deviceb\x06proto3"

var (
	file_employee_service_requests_device_rpc_get_device_proto_rawDescOnce sync.Once
	file_employee_service_requests_device_rpc_get_device_proto_rawDescData []byte
)

func file_employee_service_requests_device_rpc_get_device_proto_rawDescGZIP() []byte {
	file_employee_service_requests_device_rpc_get_device_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_device_rpc_get_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_get_device_proto_rawDesc), len(file_employee_service_requests_device_rpc_get_device_proto_rawDesc)))
	})
	return file_employee_service_requests_device_rpc_get_device_proto_rawDescData
}

var file_employee_service_requests_device_rpc_get_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_device_rpc_get_device_proto_goTypes = []any{
	(*GetDeviceRequest)(nil),  // 0: employee_service.requests.device.get_device.GetDeviceRequest
	(*GetDeviceResponse)(nil), // 1: employee_service.requests.device.get_device.GetDeviceResponse
	(*models.Device)(nil),     // 2: employee_service.models.device.Device
}
var file_employee_service_requests_device_rpc_get_device_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.device.get_device.GetDeviceResponse.device:type_name -> employee_service.models.device.Device
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_device_rpc_get_device_proto_init() }
func file_employee_service_requests_device_rpc_get_device_proto_init() {
	if File_employee_service_requests_device_rpc_get_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_device_rpc_get_device_proto_rawDesc), len(file_employee_service_requests_device_rpc_get_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_device_rpc_get_device_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_device_rpc_get_device_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_device_rpc_get_device_proto_msgTypes,
	}.Build()
	File_employee_service_requests_device_rpc_get_device_proto = out.File
	file_employee_service_requests_device_rpc_get_device_proto_goTypes = nil
	file_employee_service_requests_device_rpc_get_device_proto_depIdxs = nil
}
