// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/action/rpc_get_action.proto

package action

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionRequest) Reset() {
	*x = GetActionRequest{}
	mi := &file_employee_service_requests_action_rpc_get_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionRequest) ProtoMessage() {}

func (x *GetActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_action_rpc_get_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionRequest.ProtoReflect.Descriptor instead.
func (*GetActionRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_action_rpc_get_action_proto_rawDescGZIP(), []int{0}
}

func (x *GetActionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *models.Action         `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionResponse) Reset() {
	*x = GetActionResponse{}
	mi := &file_employee_service_requests_action_rpc_get_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionResponse) ProtoMessage() {}

func (x *GetActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_action_rpc_get_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionResponse.ProtoReflect.Descriptor instead.
func (*GetActionResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_action_rpc_get_action_proto_rawDescGZIP(), []int{1}
}

func (x *GetActionResponse) GetAction() *models.Action {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_employee_service_requests_action_rpc_get_action_proto protoreflect.FileDescriptor

const file_employee_service_requests_action_rpc_get_action_proto_rawDesc = "" +
	"\n" +
	"5employee-service/requests/action/rpc_get_action.proto\x12+employee_service.requests.action.get_action\x1a$employee-service/models/action.proto\"\"\n" +
	"\x10GetActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\x11GetActionResponse\x12>\n" +
	"\x06action\x18\x01 \x01(\v2&.employee_service.models.action.ActionR\x06actionBNZLgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/actionb\x06proto3"

var (
	file_employee_service_requests_action_rpc_get_action_proto_rawDescOnce sync.Once
	file_employee_service_requests_action_rpc_get_action_proto_rawDescData []byte
)

func file_employee_service_requests_action_rpc_get_action_proto_rawDescGZIP() []byte {
	file_employee_service_requests_action_rpc_get_action_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_action_rpc_get_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_action_rpc_get_action_proto_rawDesc), len(file_employee_service_requests_action_rpc_get_action_proto_rawDesc)))
	})
	return file_employee_service_requests_action_rpc_get_action_proto_rawDescData
}

var file_employee_service_requests_action_rpc_get_action_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_action_rpc_get_action_proto_goTypes = []any{
	(*GetActionRequest)(nil),  // 0: employee_service.requests.action.get_action.GetActionRequest
	(*GetActionResponse)(nil), // 1: employee_service.requests.action.get_action.GetActionResponse
	(*models.Action)(nil),     // 2: employee_service.models.action.Action
}
var file_employee_service_requests_action_rpc_get_action_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.action.get_action.GetActionResponse.action:type_name -> employee_service.models.action.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_action_rpc_get_action_proto_init() }
func file_employee_service_requests_action_rpc_get_action_proto_init() {
	if File_employee_service_requests_action_rpc_get_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_action_rpc_get_action_proto_rawDesc), len(file_employee_service_requests_action_rpc_get_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_action_rpc_get_action_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_action_rpc_get_action_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_action_rpc_get_action_proto_msgTypes,
	}.Build()
	File_employee_service_requests_action_rpc_get_action_proto = out.File
	file_employee_service_requests_action_rpc_get_action_proto_goTypes = nil
	file_employee_service_requests_action_rpc_get_action_proto_depIdxs = nil
}
