// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/attendance/rpc_create_attendance.proto

package attendance

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeIn        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timeIn,proto3" json:"timeIn,omitempty"`
	EmployeeId    int64                  `protobuf:"varint,2,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	ActionId      int64                  `protobuf:"varint,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttendanceRequest) Reset() {
	*x = CreateAttendanceRequest{}
	mi := &file_employee_service_requests_attendance_rpc_create_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttendanceRequest) ProtoMessage() {}

func (x *CreateAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_attendance_rpc_create_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttendanceRequest.ProtoReflect.Descriptor instead.
func (*CreateAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAttendanceRequest) GetTimeIn() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeIn
	}
	return nil
}

func (x *CreateAttendanceRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateAttendanceRequest) GetActionId() int64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

type CreateAttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendance    *models.Attendance     `protobuf:"bytes,1,opt,name=attendance,proto3" json:"attendance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttendanceResponse) Reset() {
	*x = CreateAttendanceResponse{}
	mi := &file_employee_service_requests_attendance_rpc_create_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttendanceResponse) ProtoMessage() {}

func (x *CreateAttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_attendance_rpc_create_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttendanceResponse.ProtoReflect.Descriptor instead.
func (*CreateAttendanceResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAttendanceResponse) GetAttendance() *models.Attendance {
	if x != nil {
		return x.Attendance
	}
	return nil
}

var File_employee_service_requests_attendance_rpc_create_attendance_proto protoreflect.FileDescriptor

const file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDesc = "" +
	"\n" +
	"@employee-service/requests/attendance/rpc_create_attendance.proto\x126employee_service.requests.attendance.create_attendance\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(employee-service/models/attendance.proto\"\x89\x01\n" +
	"\x17CreateAttendanceRequest\x122\n" +
	"\x06timeIn\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06timeIn\x12\x1e\n" +
	"\n" +
	"employeeId\x18\x02 \x01(\x03R\n" +
	"employeeId\x12\x1a\n" +
	"\bactionId\x18\x03 \x01(\x03R\bactionId\"j\n" +
	"\x18CreateAttendanceResponse\x12N\n" +
	"\n" +
	"attendance\x18\x01 \x01(\v2..employee_service.models.attendance.AttendanceR\n" +
	"attendanceBRZPgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/attendanceb\x06proto3"

var (
	file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescOnce sync.Once
	file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescData []byte
)

func file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescGZIP() []byte {
	file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDesc), len(file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDesc)))
	})
	return file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDescData
}

var file_employee_service_requests_attendance_rpc_create_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_attendance_rpc_create_attendance_proto_goTypes = []any{
	(*CreateAttendanceRequest)(nil),  // 0: employee_service.requests.attendance.create_attendance.CreateAttendanceRequest
	(*CreateAttendanceResponse)(nil), // 1: employee_service.requests.attendance.create_attendance.CreateAttendanceResponse
	(*timestamppb.Timestamp)(nil),    // 2: google.protobuf.Timestamp
	(*models.Attendance)(nil),        // 3: employee_service.models.attendance.Attendance
}
var file_employee_service_requests_attendance_rpc_create_attendance_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.attendance.create_attendance.CreateAttendanceRequest.timeIn:type_name -> google.protobuf.Timestamp
	3, // 1: employee_service.requests.attendance.create_attendance.CreateAttendanceResponse.attendance:type_name -> employee_service.models.attendance.Attendance
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_employee_service_requests_attendance_rpc_create_attendance_proto_init() }
func file_employee_service_requests_attendance_rpc_create_attendance_proto_init() {
	if File_employee_service_requests_attendance_rpc_create_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDesc), len(file_employee_service_requests_attendance_rpc_create_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_attendance_rpc_create_attendance_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_attendance_rpc_create_attendance_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_attendance_rpc_create_attendance_proto_msgTypes,
	}.Build()
	File_employee_service_requests_attendance_rpc_create_attendance_proto = out.File
	file_employee_service_requests_attendance_rpc_create_attendance_proto_goTypes = nil
	file_employee_service_requests_attendance_rpc_create_attendance_proto_depIdxs = nil
}
