// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/attendance/rpc_get_attendances.proto

package attendance

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAttendancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Size          *int32                 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendancesRequest) Reset() {
	*x = GetAttendancesRequest{}
	mi := &file_employee_service_requests_attendance_rpc_get_attendances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendancesRequest) ProtoMessage() {}

func (x *GetAttendancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_attendance_rpc_get_attendances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendancesRequest.ProtoReflect.Descriptor instead.
func (*GetAttendancesRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescGZIP(), []int{0}
}

func (x *GetAttendancesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetAttendancesRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type GetAttendancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendances   []*models.Attendance   `protobuf:"bytes,1,rep,name=attendances,proto3" json:"attendances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendancesResponse) Reset() {
	*x = GetAttendancesResponse{}
	mi := &file_employee_service_requests_attendance_rpc_get_attendances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendancesResponse) ProtoMessage() {}

func (x *GetAttendancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_attendance_rpc_get_attendances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendancesResponse.ProtoReflect.Descriptor instead.
func (*GetAttendancesResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescGZIP(), []int{1}
}

func (x *GetAttendancesResponse) GetAttendances() []*models.Attendance {
	if x != nil {
		return x.Attendances
	}
	return nil
}

var File_employee_service_requests_attendance_rpc_get_attendances_proto protoreflect.FileDescriptor

const file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDesc = "" +
	"\n" +
	">employee-service/requests/attendance/rpc_get_attendances.proto\x124employee_service.requests.attendance.get_attendances\x1a(employee-service/models/attendance.proto\"[\n" +
	"\x15GetAttendancesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x05H\x01R\x04size\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_size\"j\n" +
	"\x16GetAttendancesResponse\x12P\n" +
	"\vattendances\x18\x01 \x03(\v2..employee_service.models.attendance.AttendanceR\vattendancesBRZPgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/attendanceb\x06proto3"

var (
	file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescOnce sync.Once
	file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescData []byte
)

func file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescGZIP() []byte {
	file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDesc), len(file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDesc)))
	})
	return file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDescData
}

var file_employee_service_requests_attendance_rpc_get_attendances_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_attendance_rpc_get_attendances_proto_goTypes = []any{
	(*GetAttendancesRequest)(nil),  // 0: employee_service.requests.attendance.get_attendances.GetAttendancesRequest
	(*GetAttendancesResponse)(nil), // 1: employee_service.requests.attendance.get_attendances.GetAttendancesResponse
	(*models.Attendance)(nil),      // 2: employee_service.models.attendance.Attendance
}
var file_employee_service_requests_attendance_rpc_get_attendances_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.attendance.get_attendances.GetAttendancesResponse.attendances:type_name -> employee_service.models.attendance.Attendance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_attendance_rpc_get_attendances_proto_init() }
func file_employee_service_requests_attendance_rpc_get_attendances_proto_init() {
	if File_employee_service_requests_attendance_rpc_get_attendances_proto != nil {
		return
	}
	file_employee_service_requests_attendance_rpc_get_attendances_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDesc), len(file_employee_service_requests_attendance_rpc_get_attendances_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_attendance_rpc_get_attendances_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_attendance_rpc_get_attendances_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_attendance_rpc_get_attendances_proto_msgTypes,
	}.Build()
	File_employee_service_requests_attendance_rpc_get_attendances_proto = out.File
	file_employee_service_requests_attendance_rpc_get_attendances_proto_goTypes = nil
	file_employee_service_requests_attendance_rpc_get_attendances_proto_depIdxs = nil
}
