// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/facility/rpc_get_facility.proto

package facility

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacilityRequest) Reset() {
	*x = GetFacilityRequest{}
	mi := &file_employee_service_requests_facility_rpc_get_facility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacilityRequest) ProtoMessage() {}

func (x *GetFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_facility_rpc_get_facility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacilityRequest.ProtoReflect.Descriptor instead.
func (*GetFacilityRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_facility_rpc_get_facility_proto_rawDescGZIP(), []int{0}
}

func (x *GetFacilityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *models.Facility       `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacilityResponse) Reset() {
	*x = GetFacilityResponse{}
	mi := &file_employee_service_requests_facility_rpc_get_facility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacilityResponse) ProtoMessage() {}

func (x *GetFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_facility_rpc_get_facility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacilityResponse.ProtoReflect.Descriptor instead.
func (*GetFacilityResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_facility_rpc_get_facility_proto_rawDescGZIP(), []int{1}
}

func (x *GetFacilityResponse) GetFacility() *models.Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

var File_employee_service_requests_facility_rpc_get_facility_proto protoreflect.FileDescriptor

const file_employee_service_requests_facility_rpc_get_facility_proto_rawDesc = "" +
	"\n" +
	"9employee-service/requests/facility/rpc_get_facility.proto\x12/employee_service.requests.facility.get_facility\x1a&employee-service/models/facility.proto\"$\n" +
	"\x12GetFacilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"]\n" +
	"\x13GetFacilityResponse\x12F\n" +
	"\bfacility\x18\x01 \x01(\v2*.employee_service.models.facility.FacilityR\bfacilityBPZNgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/facilityb\x06proto3"

var (
	file_employee_service_requests_facility_rpc_get_facility_proto_rawDescOnce sync.Once
	file_employee_service_requests_facility_rpc_get_facility_proto_rawDescData []byte
)

func file_employee_service_requests_facility_rpc_get_facility_proto_rawDescGZIP() []byte {
	file_employee_service_requests_facility_rpc_get_facility_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_facility_rpc_get_facility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_facility_rpc_get_facility_proto_rawDesc), len(file_employee_service_requests_facility_rpc_get_facility_proto_rawDesc)))
	})
	return file_employee_service_requests_facility_rpc_get_facility_proto_rawDescData
}

var file_employee_service_requests_facility_rpc_get_facility_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_facility_rpc_get_facility_proto_goTypes = []any{
	(*GetFacilityRequest)(nil),  // 0: employee_service.requests.facility.get_facility.GetFacilityRequest
	(*GetFacilityResponse)(nil), // 1: employee_service.requests.facility.get_facility.GetFacilityResponse
	(*models.Facility)(nil),     // 2: employee_service.models.facility.Facility
}
var file_employee_service_requests_facility_rpc_get_facility_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.facility.get_facility.GetFacilityResponse.facility:type_name -> employee_service.models.facility.Facility
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_requests_facility_rpc_get_facility_proto_init() }
func file_employee_service_requests_facility_rpc_get_facility_proto_init() {
	if File_employee_service_requests_facility_rpc_get_facility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_facility_rpc_get_facility_proto_rawDesc), len(file_employee_service_requests_facility_rpc_get_facility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_facility_rpc_get_facility_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_facility_rpc_get_facility_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_facility_rpc_get_facility_proto_msgTypes,
	}.Build()
	File_employee_service_requests_facility_rpc_get_facility_proto = out.File
	file_employee_service_requests_facility_rpc_get_facility_proto_goTypes = nil
	file_employee_service_requests_facility_rpc_get_facility_proto_depIdxs = nil
}
