// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/requests/facility/rpc_update_facility.proto

package facility

import (
	models "github.com/nicodanke/gesty-api/shared/proto/employee-service/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateFacilityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OpenTime        *durationpb.Duration   `protobuf:"bytes,4,opt,name=openTime,proto3,oneof" json:"openTime,omitempty"`
	CloseTime       *durationpb.Duration   `protobuf:"bytes,5,opt,name=closeTime,proto3,oneof" json:"closeTime,omitempty"`
	AddressCountry  *string                `protobuf:"bytes,6,opt,name=addressCountry,proto3,oneof" json:"addressCountry,omitempty"`
	AddressState    *string                `protobuf:"bytes,7,opt,name=addressState,proto3,oneof" json:"addressState,omitempty"`
	AddressSubState *string                `protobuf:"bytes,8,opt,name=addressSubState,proto3,oneof" json:"addressSubState,omitempty"`
	AddressStreet   *string                `protobuf:"bytes,9,opt,name=addressStreet,proto3,oneof" json:"addressStreet,omitempty"`
	AddressNumber   *string                `protobuf:"bytes,10,opt,name=addressNumber,proto3,oneof" json:"addressNumber,omitempty"`
	AddressZipCode  *string                `protobuf:"bytes,11,opt,name=addressZipCode,proto3,oneof" json:"addressZipCode,omitempty"`
	AddressUnit     *string                `protobuf:"bytes,12,opt,name=addressUnit,proto3,oneof" json:"addressUnit,omitempty"`
	AddressLat      *float64               `protobuf:"fixed64,13,opt,name=addressLat,proto3,oneof" json:"addressLat,omitempty"`
	AddressLng      *float64               `protobuf:"fixed64,14,opt,name=addressLng,proto3,oneof" json:"addressLng,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateFacilityRequest) Reset() {
	*x = UpdateFacilityRequest{}
	mi := &file_employee_service_requests_facility_rpc_update_facility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacilityRequest) ProtoMessage() {}

func (x *UpdateFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_facility_rpc_update_facility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateFacilityRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_facility_rpc_update_facility_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateFacilityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFacilityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateFacilityRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateFacilityRequest) GetOpenTime() *durationpb.Duration {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *UpdateFacilityRequest) GetCloseTime() *durationpb.Duration {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *UpdateFacilityRequest) GetAddressCountry() string {
	if x != nil && x.AddressCountry != nil {
		return *x.AddressCountry
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddressState() string {
	if x != nil && x.AddressState != nil {
		return *x.AddressState
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddressSubState() string {
	if x != nil && x.AddressSubState != nil {
		return *x.AddressSubState
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddressStreet() string {
	if x != nil && x.AddressStreet != nil {
		return *x.AddressStreet
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddressNumber() string {
	if x != nil && x.AddressNumber != nil {
		return *x.AddressNumber
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddressZipCode() string {
	if x != nil && x.AddressZipCode != nil {
		return *x.AddressZipCode
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddressUnit() string {
	if x != nil && x.AddressUnit != nil {
		return *x.AddressUnit
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddressLat() float64 {
	if x != nil && x.AddressLat != nil {
		return *x.AddressLat
	}
	return 0
}

func (x *UpdateFacilityRequest) GetAddressLng() float64 {
	if x != nil && x.AddressLng != nil {
		return *x.AddressLng
	}
	return 0
}

type UpdateFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *models.Facility       `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacilityResponse) Reset() {
	*x = UpdateFacilityResponse{}
	mi := &file_employee_service_requests_facility_rpc_update_facility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacilityResponse) ProtoMessage() {}

func (x *UpdateFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_requests_facility_rpc_update_facility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacilityResponse.ProtoReflect.Descriptor instead.
func (*UpdateFacilityResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_requests_facility_rpc_update_facility_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateFacilityResponse) GetFacility() *models.Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

var File_employee_service_requests_facility_rpc_update_facility_proto protoreflect.FileDescriptor

const file_employee_service_requests_facility_rpc_update_facility_proto_rawDesc = "" +
	"\n" +
	"<employee-service/requests/facility/rpc_update_facility.proto\x122employee_service.requests.facility.update_facility\x1a&employee-service/models/facility.proto\x1a\x1egoogle/protobuf/duration.proto\"\xab\x06\n" +
	"\x15UpdateFacilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12:\n" +
	"\bopenTime\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x02R\bopenTime\x88\x01\x01\x12<\n" +
	"\tcloseTime\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x03R\tcloseTime\x88\x01\x01\x12+\n" +
	"\x0eaddressCountry\x18\x06 \x01(\tH\x04R\x0eaddressCountry\x88\x01\x01\x12'\n" +
	"\faddressState\x18\a \x01(\tH\x05R\faddressState\x88\x01\x01\x12-\n" +
	"\x0faddressSubState\x18\b \x01(\tH\x06R\x0faddressSubState\x88\x01\x01\x12)\n" +
	"\raddressStreet\x18\t \x01(\tH\aR\raddressStreet\x88\x01\x01\x12)\n" +
	"\raddressNumber\x18\n" +
	" \x01(\tH\bR\raddressNumber\x88\x01\x01\x12+\n" +
	"\x0eaddressZipCode\x18\v \x01(\tH\tR\x0eaddressZipCode\x88\x01\x01\x12%\n" +
	"\vaddressUnit\x18\f \x01(\tH\n" +
	"R\vaddressUnit\x88\x01\x01\x12#\n" +
	"\n" +
	"addressLat\x18\r \x01(\x01H\vR\n" +
	"addressLat\x88\x01\x01\x12#\n" +
	"\n" +
	"addressLng\x18\x0e \x01(\x01H\fR\n" +
	"addressLng\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_openTimeB\f\n" +
	"\n" +
	"_closeTimeB\x11\n" +
	"\x0f_addressCountryB\x0f\n" +
	"\r_addressStateB\x12\n" +
	"\x10_addressSubStateB\x10\n" +
	"\x0e_addressStreetB\x10\n" +
	"\x0e_addressNumberB\x11\n" +
	"\x0f_addressZipCodeB\x0e\n" +
	"\f_addressUnitB\r\n" +
	"\v_addressLatB\r\n" +
	"\v_addressLng\"`\n" +
	"\x16UpdateFacilityResponse\x12F\n" +
	"\bfacility\x18\x01 \x01(\v2*.employee_service.models.facility.FacilityR\bfacilityBPZNgithub.com/nicodanke/gesty-api/shared/proto/employee-service/requests/facilityb\x06proto3"

var (
	file_employee_service_requests_facility_rpc_update_facility_proto_rawDescOnce sync.Once
	file_employee_service_requests_facility_rpc_update_facility_proto_rawDescData []byte
)

func file_employee_service_requests_facility_rpc_update_facility_proto_rawDescGZIP() []byte {
	file_employee_service_requests_facility_rpc_update_facility_proto_rawDescOnce.Do(func() {
		file_employee_service_requests_facility_rpc_update_facility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_requests_facility_rpc_update_facility_proto_rawDesc), len(file_employee_service_requests_facility_rpc_update_facility_proto_rawDesc)))
	})
	return file_employee_service_requests_facility_rpc_update_facility_proto_rawDescData
}

var file_employee_service_requests_facility_rpc_update_facility_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_service_requests_facility_rpc_update_facility_proto_goTypes = []any{
	(*UpdateFacilityRequest)(nil),  // 0: employee_service.requests.facility.update_facility.UpdateFacilityRequest
	(*UpdateFacilityResponse)(nil), // 1: employee_service.requests.facility.update_facility.UpdateFacilityResponse
	(*durationpb.Duration)(nil),    // 2: google.protobuf.Duration
	(*models.Facility)(nil),        // 3: employee_service.models.facility.Facility
}
var file_employee_service_requests_facility_rpc_update_facility_proto_depIdxs = []int32{
	2, // 0: employee_service.requests.facility.update_facility.UpdateFacilityRequest.openTime:type_name -> google.protobuf.Duration
	2, // 1: employee_service.requests.facility.update_facility.UpdateFacilityRequest.closeTime:type_name -> google.protobuf.Duration
	3, // 2: employee_service.requests.facility.update_facility.UpdateFacilityResponse.facility:type_name -> employee_service.models.facility.Facility
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_employee_service_requests_facility_rpc_update_facility_proto_init() }
func file_employee_service_requests_facility_rpc_update_facility_proto_init() {
	if File_employee_service_requests_facility_rpc_update_facility_proto != nil {
		return
	}
	file_employee_service_requests_facility_rpc_update_facility_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_requests_facility_rpc_update_facility_proto_rawDesc), len(file_employee_service_requests_facility_rpc_update_facility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_requests_facility_rpc_update_facility_proto_goTypes,
		DependencyIndexes: file_employee_service_requests_facility_rpc_update_facility_proto_depIdxs,
		MessageInfos:      file_employee_service_requests_facility_rpc_update_facility_proto_msgTypes,
	}.Build()
	File_employee_service_requests_facility_rpc_update_facility_proto = out.File
	file_employee_service_requests_facility_rpc_update_facility_proto_goTypes = nil
	file_employee_service_requests_facility_rpc_update_facility_proto_depIdxs = nil
}
