// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: employee-service/models/device.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password                string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Enabled                 bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Active                  bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	ActivationCode          string                 `protobuf:"bytes,6,opt,name=activationCode,proto3" json:"activationCode,omitempty"`
	ActivationCodeExpiresAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=activationCodeExpiresAt,proto3" json:"activationCodeExpiresAt,omitempty"`
	DeviceName              string                 `protobuf:"bytes,8,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	DeviceModel             string                 `protobuf:"bytes,9,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	DeviceBrand             string                 `protobuf:"bytes,10,opt,name=deviceBrand,proto3" json:"deviceBrand,omitempty"`
	DeviceSerialNumber      string                 `protobuf:"bytes,11,opt,name=deviceSerialNumber,proto3" json:"deviceSerialNumber,omitempty"`
	DeviceOs                string                 `protobuf:"bytes,12,opt,name=deviceOs,proto3" json:"deviceOs,omitempty"`
	DeviceRam               string                 `protobuf:"bytes,13,opt,name=deviceRam,proto3" json:"deviceRam,omitempty"`
	DeviceStorage           string                 `protobuf:"bytes,14,opt,name=deviceStorage,proto3" json:"deviceStorage,omitempty"`
	DeviceOsVersion         string                 `protobuf:"bytes,15,opt,name=deviceOsVersion,proto3" json:"deviceOsVersion,omitempty"`
	FacilityId              int64                  `protobuf:"varint,16,opt,name=facilityId,proto3" json:"facilityId,omitempty"`
	ActionIds               []int64                `protobuf:"varint,17,rep,packed,name=actionIds,proto3" json:"actionIds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_employee_service_models_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_models_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_employee_service_models_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Device) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Device) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Device) GetActivationCode() string {
	if x != nil {
		return x.ActivationCode
	}
	return ""
}

func (x *Device) GetActivationCodeExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivationCodeExpiresAt
	}
	return nil
}

func (x *Device) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Device) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *Device) GetDeviceBrand() string {
	if x != nil {
		return x.DeviceBrand
	}
	return ""
}

func (x *Device) GetDeviceSerialNumber() string {
	if x != nil {
		return x.DeviceSerialNumber
	}
	return ""
}

func (x *Device) GetDeviceOs() string {
	if x != nil {
		return x.DeviceOs
	}
	return ""
}

func (x *Device) GetDeviceRam() string {
	if x != nil {
		return x.DeviceRam
	}
	return ""
}

func (x *Device) GetDeviceStorage() string {
	if x != nil {
		return x.DeviceStorage
	}
	return ""
}

func (x *Device) GetDeviceOsVersion() string {
	if x != nil {
		return x.DeviceOsVersion
	}
	return ""
}

func (x *Device) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *Device) GetActionIds() []int64 {
	if x != nil {
		return x.ActionIds
	}
	return nil
}

var File_employee_service_models_device_proto protoreflect.FileDescriptor

const file_employee_service_models_device_proto_rawDesc = "" +
	"\n" +
	"$employee-service/models/device.proto\x12\x1eemployee_service.models.device\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x04\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12&\n" +
	"\x0eactivationCode\x18\x06 \x01(\tR\x0eactivationCode\x12T\n" +
	"\x17activationCodeExpiresAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x17activationCodeExpiresAt\x12\x1e\n" +
	"\n" +
	"deviceName\x18\b \x01(\tR\n" +
	"deviceName\x12 \n" +
	"\vdeviceModel\x18\t \x01(\tR\vdeviceModel\x12 \n" +
	"\vdeviceBrand\x18\n" +
	" \x01(\tR\vdeviceBrand\x12.\n" +
	"\x12deviceSerialNumber\x18\v \x01(\tR\x12deviceSerialNumber\x12\x1a\n" +
	"\bdeviceOs\x18\f \x01(\tR\bdeviceOs\x12\x1c\n" +
	"\tdeviceRam\x18\r \x01(\tR\tdeviceRam\x12$\n" +
	"\rdeviceStorage\x18\x0e \x01(\tR\rdeviceStorage\x12(\n" +
	"\x0fdeviceOsVersion\x18\x0f \x01(\tR\x0fdeviceOsVersion\x12\x1e\n" +
	"\n" +
	"facilityId\x18\x10 \x01(\x03R\n" +
	"facilityId\x12\x1c\n" +
	"\tactionIds\x18\x11 \x03(\x03R\tactionIdsBEZCgithub.com/nicodanke/gesty-api/shared/proto/employee-service/modelsb\x06proto3"

var (
	file_employee_service_models_device_proto_rawDescOnce sync.Once
	file_employee_service_models_device_proto_rawDescData []byte
)

func file_employee_service_models_device_proto_rawDescGZIP() []byte {
	file_employee_service_models_device_proto_rawDescOnce.Do(func() {
		file_employee_service_models_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_models_device_proto_rawDesc), len(file_employee_service_models_device_proto_rawDesc)))
	})
	return file_employee_service_models_device_proto_rawDescData
}

var file_employee_service_models_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_employee_service_models_device_proto_goTypes = []any{
	(*Device)(nil),                // 0: employee_service.models.device.Device
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_employee_service_models_device_proto_depIdxs = []int32{
	1, // 0: employee_service.models.device.Device.activationCodeExpiresAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_service_models_device_proto_init() }
func file_employee_service_models_device_proto_init() {
	if File_employee_service_models_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_models_device_proto_rawDesc), len(file_employee_service_models_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_service_models_device_proto_goTypes,
		DependencyIndexes: file_employee_service_models_device_proto_depIdxs,
		MessageInfos:      file_employee_service_models_device_proto_msgTypes,
	}.Build()
	File_employee_service_models_device_proto = out.File
	file_employee_service_models_device_proto_goTypes = nil
	file_employee_service_models_device_proto_depIdxs = nil
}
